io/plugins/eu.esdihumboldt.hale.io.appschema.test/src/eu/esdihumboldt/hale/io/appschema/writer/AppSchemaMappingTest.java, io/plugins/eu.esdihumboldt.hale.io.appschema/META-INF/MANIFEST.MF, io/plugins/eu.esdihumboldt.hale.io.appschema/src/eu/esdihumboldt/hale/io/appschema/writer/internal/AbstractPropertyTransformationHandler.java
As [discussed](https://github.com/ridethepenguin/hale/issues/15), makes sure an element with a constant attribute is always encoded.
=> Set encodeIfEmpty=true if attribute has constant value

io/plugins/eu.esdihumboldt.hale.io.appschema/src/eu/esdihumboldt/hale/io/appschema/writer/internal/AbstractPropertyTransformationHandler.java
@stempler This should fix the issue with nested nillable mandatory elements we discussed this morning, am I too late to see it in the release (after your confirmation that it really works... I made a few tests myself but I could really use a double check here)?
=> Fixed encodeIfEmpty handling for nillable mandatory elements

common/plugins/eu.esdihumboldt.hale.common.align/src/eu/esdihumboldt/hale/common/align/model/impl/AbstractCellExplanation.java, common/plugins/eu.esdihumboldt.hale.common.align/src/eu/esdihumboldt/hale/common/align/model/impl/mdexpl/MarkdownCellExplanation.java, cst/plugins/eu.esdihumboldt.cst.functions.custom/src/eu/esdihumboldt/hale/common/align/custom/DefaultCustomFunctionExplanation.java
Fixes German content being used for English language if the default locale is German.
=> don't prefer default locale over root locale

common/plugins/eu.esdihumboldt.hale.common.instance.orient/src/eu/esdihumboldt/hale/common/instance/orient/storage/StoreInstancesJob.java, io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/reader/internal/StreamGmlReader.java, io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/reader/internal/wfs/WFSException.groovy, io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/reader/internal/wfs/WfsBackedGmlInstanceCollection.java
refs #188
- Use RESULTTYPE=hits query to determine total number of features but do not fail if WFS server does not include a numberOfFeatures/numberMatched attribute in its response
- While storing instances, use InstanceCollection.size() to display total number of features to the user if hasSize() is true
- In case of a communication/processing failure, report exception message
=> Do not rely on numberOfFeatures/numberMatched attributes

common/plugins/eu.esdihumboldt.hale.common.instance/src/eu/esdihumboldt/hale/common/instance/model/InstanceResolver.java, common/plugins/eu.esdihumboldt.hale.common.instance/src/eu/esdihumboldt/hale/common/instance/model/impl/ReferenceInstanceCollection.java, cst/plugins/eu.esdihumboldt.cst.functions.core/src/eu/esdihumboldt/cst/functions/core/merge/AbstractMergeHandler.java, cst/plugins/eu.esdihumboldt.cst.functions.core/src/eu/esdihumboldt/cst/functions/core/merge/PropertiesMergeHandler.java, io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/reader/internal/GmlInstanceCollection.java, ui/plugins/eu.esdihumboldt.hale.ui.views.mapping/src/eu/esdihumboldt/hale/ui/views/mapping/MappingView.java
refs #225
Improves the memory consumption for large merges, especially if much of the data of the individual instances does not end up in the merged source instance.
Performance is likely lower than before, because the check if a value is unique now has to be done for each instance against all values that have been added before.
Changes the behavior of "auto-detect" slightly, with auto detect now for all properties only unique values are retained. As with the other aspects if the merge this is still restricted to first level properties.
=> incremental merging of instances

io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/reader/internal/wfs/WfsBackedGmlInstanceCollection.java
- If the server reports the number of results in the numberMatched attribute, do not process more results than that
- Set value of size correctly if numberMatched is larger than maxNumberOfFeatures
=> Prevent loading more results than reported by the WFS

build/gradle/deployArtifacts.gradle, common/plugins/eu.esdihumboldt.hale.common.headless/src/eu/esdihumboldt/hale/common/headless/HeadlessIO.java
Add wetransform artifactory for dependency resolution. Also prevents NullPointerException in case `loadProvider` returns null.
=> Fix master build / Prevent NPE in HeadlessIO

common/plugins/eu.esdihumboldt.hale.common.instance.groovy.test/src/eu/esdihumboldt/hale/common/instance/groovy/InstanceAccessorTest.groovy, common/plugins/eu.esdihumboldt.hale.common.instance.groovy/src/eu/esdihumboldt/hale/common/instance/groovy/InstanceAccessor.groovy, cst/plugins/eu.esdihumboldt.cst.functions.core/src/eu/esdihumboldt/cst/functions/core/merge/PropertiesMergeHandler.java, util/plugins/eu.esdihumboldt.util.groovy/src/eu/esdihumboldt/util/groovy/paths/PathWithNulls.java
Added two ways of dealing with nulls in InstanceAccessor:
- treat null values as non-existing values (default behavior)
- treat null values as they are and list them
There is no way though to discern no value and a null value even with the later setting, if the `first()` or `value()` access methods are used.
=> allow null values in InstanceAccessor

build/gradle/deployArtifacts.gradle, io/plugins/eu.esdihumboldt.hale.io.schematron/META-INF/MANIFEST.MF
...to be able to have correct dependencies for Maven artifacts of bundles
that bundle libraries internally.
Added extra dependency for schematron bundle.
As a result it should be possible to remove the `org.opengis.cite:schema-utils:1.8` dependency in https://github.com/halestudio/hale-cli/pull/24.
=> support for extra dependencies defined in manifest

cst/plugins/eu.esdihumboldt.cst.functions.geometric/src/eu/esdihumboldt/cst/functions/geometric/GeometryHelperFunctions.groovy, io/plugins/eu.esdihumboldt.hale.io.gml.test/src/eu/esdihumboldt/hale/io/gml/writer/internal/StreamGmlWriterTest2.groovy
Groovy compiler complains about accessing methods of  the `geometry`property of
methods returning `GeometryProperty<?>`.
An alternative solution where we would be able to keep the `@CompileStatic`s would 
be to let all relevant methods return `GeometryProperty<? extends Geometry>`
instead.
=> Prevent static compile errors

common/plugins/eu.esdihumboldt.hale.common.core/src/eu/esdihumboldt/hale/common/core/report/writer/ReportReader.java, ui/plugins/eu.esdihumboldt.hale.ui.views.report/src/eu/esdihumboldt/hale/ui/views/report/ReportListLabelProvider.java
- Being unable to determine a report session ID from a file name is not an error
- Don't use formatted date for report session with ID/timestamp 0
=> improve handling of loaded reports

build/gradle/deployArtifacts.gradle
With SNAPSHOT dependencies the `:uploadEclipse` stage fails because those dependencies cannot be resolved.
=> Make SNAPSHOT dependencies resolvable in master build

ui/features/eu.esdihumboldt.hale.ui.feature/feature.xml
Remove `Load project from template...` funcionality in the course of
hale connect integration (see #293).
=> Remove plugin e.e.h.ui.templates from UI feature

ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/function/common/PropertyEntitySelector.java, ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/function/generic/pages/PropertyEntitiesPage.java, ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/function/generic/pages/internal/PropertyField.java
When the source or target type of a cell is changed, the `parentType` of the corresponding property selectors needs to be updated to allow subsequent selection of the properties of the newly selected type.
This update failed (as reported in #72), because the method used to update  the `parentType` has side effects, i.e. it modifies the list of property selectors  to remove previously selected properties when the `parentType` changes.
This fix replaces the iterator-based approach of updating the property selectors by one that is safe with regards to the side effects of `setParentType`.
=> Fix updating parentType of property selectors after type change

app/plugins/eu.esdihumboldt.hale.app.transform/src/eu/esdihumboldt/hale/app/transform/ExecApplication.groovy, app/plugins/eu.esdihumboldt.hale.app.transform/src/eu/esdihumboldt/hale/app/transform/ExecTransformation.java, common/plugins/eu.esdihumboldt.hale.common.align/plugin.xml, common/plugins/eu.esdihumboldt.hale.common.align/src/eu/esdihumboldt/hale/common/align/io/impl/AbstractAlignmentReader.java, common/plugins/eu.esdihumboldt.hale.common.align/src/eu/esdihumboldt/hale/common/align/io/impl/CastorAlignmentReader.java, common/plugins/eu.esdihumboldt.hale.common.align/src/eu/esdihumboldt/hale/common/align/io/impl/CastorAlignmentWriter.java, common/plugins/eu.esdihumboldt.hale.common.align/src/eu/esdihumboldt/hale/common/align/io/impl/JaxbAlignmentReader.java, common/plugins/eu.esdihumboldt.hale.common.align/src/eu/esdihumboldt/hale/common/align/io/impl/JaxbAlignmentWriter.java, common/plugins/eu.esdihumboldt.hale.common.align/src/eu/esdihumboldt/hale/common/align/io/impl/JaxbBaseAlignmentReader.java, common/plugins/eu.esdihumboldt.hale.common.core/plugin.xml, common/plugins/eu.esdihumboldt.hale.common.core/src/eu/esdihumboldt/hale/common/core/HalePlatform.java, common/plugins/eu.esdihumboldt.hale.common.core/src/eu/esdihumboldt/hale/common/core/io/project/ProjectIO.java, common/plugins/eu.esdihumboldt.hale.common.core/src/eu/esdihumboldt/hale/common/core/io/project/impl/AbstractProjectReader.java, common/plugins/eu.esdihumboldt.hale.common.schema.persist/plugin.xml, common/plugins/eu.esdihumboldt.hale.common.schema.persist/src/eu/esdihumboldt/hale/common/schema/persist/hsd/HaleSchemaReader.java, common/plugins/eu.esdihumboldt.hale.common.schema.persist/src/eu/esdihumboldt/hale/common/schema/persist/hsd/HaleSchemaWriter.java, common/plugins/eu.esdihumboldt.hale.common.schema.persist/src/eu/esdihumboldt/hale/common/schema/persist/hsd/json/HaleSchemaReaderJson.java, common/plugins/eu.esdihumboldt.hale.common.schema.persist/src/eu/esdihumboldt/hale/common/schema/persist/hsd/json/HaleSchemaWriterJson.java, ext/styledmap/eu.esdihumboldt.hale.ui.views.styledmap/plugin.xml, io/plugins/eu.esdihumboldt.hale.io.appschema/src/eu/esdihumboldt/hale/io/appschema/writer/AbstractAppSchemaConfigurator.java, io/plugins/eu.esdihumboldt.hale.io.csv/src/eu/esdihumboldt/hale/io/csv/writer/internal/CSVAlignmentMappingWriter.java, io/plugins/eu.esdihumboldt.hale.io.jdbc.spatialite/src/eu/esdihumboldt/hale/io/jdbc/spatialite/internal/SpatiaLiteHelper.java, io/plugins/eu.esdihumboldt.hale.io.oml/src/eu/esdihumboldt/hale/io/oml/helper/NotSupportedTranslator.java, io/plugins/eu.esdihumboldt.hale.io.xls/src/eu/esdihumboldt/hale/io/xls/writer/XLSAlignmentMappingWriter.java, ui/plugins/eu.esdihumboldt.hale.ui.application/plugin.xml, ui/plugins/eu.esdihumboldt.hale.ui.firststeps/plugin.xml, ui/plugins/eu.esdihumboldt.hale.ui.util/plugin.xml, ui/plugins/eu.esdihumboldt.hale.ui/plugin.xml
Replace product name in the GUI, as outlined in #310.
=> Replace "HALE" with "hale"/"hale studio" in GUI

io/plugins/eu.esdihumboldt.hale.io.haleconnect.ui/src/eu/esdihumboldt/hale/io/haleconnect/ui/preferences/HaleConnectExtendedPreferencePage.java, io/plugins/eu.esdihumboldt.hale.io.haleconnect.ui/src/eu/esdihumboldt/hale/io/haleconnect/ui/preferences/PreferenceConstants.java, io/plugins/eu.esdihumboldt.hale.io.haleconnect.ui/src/eu/esdihumboldt/hale/io/haleconnect/ui/preferences/PreferenceInitializer.java
Allow activating the default base paths for hale connect via a checkbox in the extended preferences page. This will allow easier migration in the future in case the DNS names of the endpoints change.
=> Add global switch to activate baked-in defaults for hale connect base paths

common/plugins/eu.esdihumboldt.hale.common.schema/src/eu/esdihumboldt/hale/common/schema/model/impl/AbstractGroupPropertyDecorator.java, io/plugins/eu.esdihumboldt.hale.io.xsd/src/eu/esdihumboldt/hale/io/xsd/reader/internal/SubstitutionProperty.java
when using hale-api for analysis of the data schema, access to the origin properties is required.
=> make decorated properties public accessible

common/plugins/eu.esdihumboldt.hale.common.core/src/eu/esdihumboldt/hale/common/core/io/supplier/MultiLocationOutputSupplier.java, io/plugins/eu.esdihumboldt.hale.io.gml.ui/plugin.xml, io/plugins/eu.esdihumboldt.hale.io.gml.ui/src/eu/esdihumboldt/hale/io/gml/ui/PartitionConfigurationPage.java, io/plugins/eu.esdihumboldt.hale.io.gml/META-INF/MANIFEST.MF, io/plugins/eu.esdihumboldt.hale.io.gml/plugin.xml, io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/writer/internal/StreamGmlWriter.java, io/plugins/eu.esdihumboldt.hale.io.wfs/plugin.xml, io/plugins/eu.esdihumboldt.hale.io.wfs/src/eu/esdihumboldt/hale/io/wfs/file/WFSFeatureCollectionWriter.java, ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/io/instance/InstanceExportWizard.java
Add basic support for partitioning GML to multiple output files. This covers the basic requirements laid out in #331 which keeps all inter-related objects together in one part, regardless of the given number of maximum features per file.
Support for validating all generated output files is also added by replacing the original `LocatableOutputSupplier` object on-the-fly with a `MultiLocationOutputSupplier` as a hint for the validation mechanism that multiple files need to be validated.
=> Add support for partitioning GML to multiple files

io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/reader/internal/GmlInstanceCollection.java, io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/reader/internal/StreamGmlReader.java, io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/reader/internal/instance/StreamGmlHelper.java
Ignoring the mapping relevant types setting allows to read objects that are not by default classified as mapping relevant. Only makes sense though if used with the GML reader.
Suppressing the parsing of geometries allows rewriting the geometries in their original form.
=> enhancements for rewriting GML files

ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/service/project/internal/ProjectServiceImpl.java
Guard against cases where the ProjectWriter does not have a target location or
the target location is not a file.
=> Treat save as export in case of non-file target

io/plugins/eu.esdihumboldt.hale.io.appschema.test/src/eu/esdihumboldt/hale/io/geoserver/rest/ResourceManagerIT.java
Tests fail since INSPIRE schema URLs were moved to HTTPS
=> Skip Geoserver tests

io/plugins/eu.esdihumboldt.hale.io.haleconnect.ui/plugin.xml, io/plugins/eu.esdihumboldt.hale.io.haleconnect.ui/src/eu/esdihumboldt/hale/io/haleconnect/ui/projects/ChooseHaleConnectProjectWizardPage.java, io/plugins/eu.esdihumboldt.hale.io.haleconnect.ui/src/eu/esdihumboldt/hale/io/haleconnect/ui/projects/HaleConnectProjectConfig.groovy, io/plugins/eu.esdihumboldt.hale.io.haleconnect.ui/src/eu/esdihumboldt/hale/io/haleconnect/ui/projects/HaleConnectProjectExportAdvisor.java, io/plugins/eu.esdihumboldt.hale.io.haleconnect.ui/src/eu/esdihumboldt/hale/io/haleconnect/ui/projects/HaleConnectTarget.java, io/plugins/eu.esdihumboldt.hale.io.haleconnect/plugin.xml, io/plugins/eu.esdihumboldt.hale.io.haleconnect/src/eu/esdihumboldt/hale/io/haleconnect/HaleConnectInputSupplier.java, io/plugins/eu.esdihumboldt.hale.io.haleconnect/src/eu/esdihumboldt/hale/io/haleconnect/HaleConnectProjectInfo.java, io/plugins/eu.esdihumboldt.hale.io.haleconnect/src/eu/esdihumboldt/hale/io/haleconnect/HaleConnectService.java, io/plugins/eu.esdihumboldt.hale.io.haleconnect/src/eu/esdihumboldt/hale/io/haleconnect/internal/HaleConnectServiceImpl.java, io/plugins/eu.esdihumboldt.hale.io.haleconnect/src/eu/esdihumboldt/hale/io/haleconnect/project/HaleConnectProjectReader.java, io/plugins/eu.esdihumboldt.hale.io.haleconnect/src/eu/esdihumboldt/hale/io/haleconnect/project/HaleConnectProjectWriter.java
The `lastModified` timestamp of the project bucket is now stored in the project properties when importing a project from hale connect. When a user wants to update the hale connect project later, that timestamp is checked against the current `lastModified` of the project bucket to check if the upstream project changed in the meantime. In case of a change, or if no timestamp is stored in the exported project, a warning is displayed. Refs #372
=> Add warning in export wizard when upstream hale connect has changed

common/plugins/eu.esdihumboldt.hale.common.schema/schema/eu.esdihumboldt.hale.schema.valueconstraint.exsd, io/plugins/eu.esdihumboldt.hale.io.jdbc/plugin.xml, io/plugins/eu.esdihumboldt.hale.io.xsd/plugin.xml
For compatibility with MongoDB.
Extensions like the pro plugins also need to be adapted accordingly.
=> don't use dots in value constraint IDs

common/plugins/eu.esdihumboldt.hale.common.core/src/eu/esdihumboldt/hale/common/core/io/HaleIO.java, common/plugins/eu.esdihumboldt.hale.common.core/src/eu/esdihumboldt/hale/common/core/io/project/ProjectWriter.java, common/plugins/eu.esdihumboldt.hale.common.core/src/eu/esdihumboldt/hale/common/core/io/project/impl/AbstractProjectWriter.java, common/plugins/eu.esdihumboldt.hale.common.core/src/eu/esdihumboldt/hale/common/core/io/report/MutableTargetIOReport.java, common/plugins/eu.esdihumboldt.hale.common.core/src/eu/esdihumboldt/hale/common/core/io/report/impl/DefaultIOReporter.java, io/plugins/eu.esdihumboldt.hale.io.haleconnect.ui/src/eu/esdihumboldt/hale/io/haleconnect/ui/projects/HaleConnectTarget.java, io/plugins/eu.esdihumboldt.hale.io.haleconnect/plugin.xml, io/plugins/eu.esdihumboldt.hale.io.haleconnect/src/eu/esdihumboldt/hale/io/haleconnect/HaleConnectInputSupplier.java, io/plugins/eu.esdihumboldt.hale.io.haleconnect/src/eu/esdihumboldt/hale/io/haleconnect/HaleConnectProjectInfo.java, io/plugins/eu.esdihumboldt.hale.io.haleconnect/src/eu/esdihumboldt/hale/io/haleconnect/internal/HaleConnectServiceImpl.java, io/plugins/eu.esdihumboldt.hale.io.haleconnect/src/eu/esdihumboldt/hale/io/haleconnect/project/HaleConnectProjectReader.java, io/plugins/eu.esdihumboldt.hale.io.haleconnect/src/eu/esdihumboldt/hale/io/haleconnect/project/HaleConnectProjectWriter.java, ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/io/project/SaveProjectWizard.java, ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/service/project/ProjectResourcesUtil.java, ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/service/project/internal/ProjectServiceImpl.java
Introduces the possibility to save changes directly to hale connect (#422). ~Currently limited to projects that were imported from hale connect.~ Also adds support for saving a project to hale connect and having subsequent saves update the remote project (#429).
~Currently also includes changes from PRs #424 and #426. To be rebased after these have been merged.~
=> Save projects to hale connect

ui/plugins/eu.esdihumboldt.hale.ui.application/HALE.product
Because the `-name` argument was not updated when the application title was changed to `hale studio`, opening a file that is specified on the command line no longer worked.
=> Fix opening a file when launching

CHANGELOG.md, io/plugins/eu.esdihumboldt.hale.io.haleconnect.ui/src/eu/esdihumboldt/hale/io/haleconnect/ui/templates/welcome-login.vm
If either the user name or the password contained special characters like '%', the entered values were not passed correctly to the hale connect login API.
=> Fix hale connect login on Welcome Page

common/plugins/eu.esdihumboldt.hale.common.core/src/eu/esdihumboldt/hale/common/core/io/PathUpdate.java
The case when `oldRaw` is empty was not considered before
=> Prevent replacing empty String

io/plugins/eu.esdihumboldt.hale.io.haleconnect.ui/src/eu/esdihumboldt/hale/io/haleconnect/ui/internal/HaleConnectUIPlugin.java, io/plugins/eu.esdihumboldt.hale.io.haleconnect.ui/src/eu/esdihumboldt/hale/io/haleconnect/ui/preferences/PreferenceInitializer.java
Adapts the hale connect endpoints to the new URL scheme of the swarm deployment and fixes an issue with loading the default endpoints when a user had defined custom endpoints previously.
@stempler I used `https://haleconnect.com/<service>` as the new URL scheme (not `*www*.haleconnect.com/<service>`). Is that correct?
=> Update default hale connect endpoints

common/plugins/eu.esdihumboldt.hale.common.align.test/src/eu/esdihumboldt/hale/common/align/io/JaxbAlignmentIOTest.java, common/plugins/eu.esdihumboldt.hale.common.align/src/eu/esdihumboldt/hale/common/align/io/impl/JaxbAlignmentIO.java, common/plugins/eu.esdihumboldt.hale.common.align/src/eu/esdihumboldt/hale/common/align/io/impl/JaxbAlignmentReader.java, common/plugins/eu.esdihumboldt.hale.common.align/src/eu/esdihumboldt/hale/common/align/io/impl/internal/AbstractBaseAlignmentLoader.java, common/plugins/eu.esdihumboldt.hale.common.align/src/eu/esdihumboldt/hale/common/align/io/impl/internal/JaxbToAlignment.java, common/plugins/eu.esdihumboldt.hale.common.align/src/eu/esdihumboldt/hale/common/align/migrate/AlignmentMigrationNameLookupSupport.java, common/plugins/eu.esdihumboldt.hale.common.align/src/eu/esdihumboldt/hale/common/align/migrate/impl/UnmigratedCell.java, common/plugins/eu.esdihumboldt.hale.common.align/src/eu/esdihumboldt/hale/common/align/model/functions/merge/MergeMigrator.java, common/plugins/eu.esdihumboldt.hale.common.align/src/eu/esdihumboldt/hale/common/align/model/impl/MutableCellDecorator.java, common/plugins/eu.esdihumboldt.hale.common.test/src/eu/esdihumboldt/hale/common/test/TestUtil.java
When importing an alignment that includes types and/or properties that do not have a matching type/property in the source/target schemas, hale studio offers remapping these missing types/properties to existing ones. Until now, when a remapping was done on a property that was at the same time a merge property or join condition, the respective transformation parameters were not updated and needed to be changed manually (see #428).
This patch modifies the remapping of the imported alignment so that the for every cell its respective `CellMigrator` is used to make sure that transformation parameters are migrated as well.
=> Support migration of Merge, Join parameters when remapping schemas

CHANGELOG.md, common/plugins/eu.esdihumboldt.hale.common.instance/src/eu/esdihumboldt/hale/common/instance/geometry/CRSProvider.java, common/plugins/eu.esdihumboldt.hale.common.instance/src/eu/esdihumboldt/hale/common/instance/geometry/impl/AbstractCRSManager.java, common/plugins/eu.esdihumboldt.hale.common.instance/src/eu/esdihumboldt/hale/common/instance/geometry/impl/EPSGResolveCache.java, common/plugins/eu.esdihumboldt.hale.common.instance/src/eu/esdihumboldt/hale/common/instance/io/impl/AbstractInstanceReader.java, io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/reader/internal/instance/StreamGmlHelper.java, io/plugins/eu.esdihumboldt.hale.io.jdbc/META-INF/MANIFEST.MF, io/plugins/eu.esdihumboldt.hale.io.shp/src/eu/esdihumboldt/hale/io/shp/reader/internal/ShapesInstanceCollection.java, ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/io/instance/crs/DialogCRSProvider.java
This fixes a bug in `EPSGResolveCache` that prevented the CRS database lookup to work properly. This will usually prevent the `missing Bursa-Wolf parameters` exception (#281) in cases where the `.prj` file contains an incomplete WKT definition but Geotools can map it to an EPSG code nonetheless.
In cases where Geotools can't map the WKT definition to an EPSG code, the CRS dialog prompt will now be forced, so that the user can select an EPSG code, or, in cases where none exists, provide a WKT definition.
=> Improve CRS lookup for shapefiles

common/plugins/eu.esdihumboldt.hale.common.instance/src/eu/esdihumboldt/hale/common/instance/geometry/CRSDefinitionUtil.java, common/plugins/eu.esdihumboldt.hale.common.instance/src/eu/esdihumboldt/hale/common/instance/geometry/impl/EPSGResolveCache.java
After the changes of #480, there were suddenly occasional axis flip problems when importing shapefiles. This patch improves the CRS lookup so that the axis order of the projection file is passed on to Geotools. Interestingly, Geotools honours the `longitudeFirst` parameter only for codes prefixed with `EPSG:` but not for those prefixed with `urn:ogc:def:crs:EPSG::`.
=> Refactor CRS resolution to avoid axis flip

CHANGELOG.md, io/plugins/eu.esdihumboldt.hale.io.haleconnect.ui/plugin.xml, io/plugins/eu.esdihumboldt.hale.io.haleconnect.ui/src/eu/esdihumboldt/hale/io/haleconnect/ui/HaleConnectLoginHandler.java, io/plugins/eu.esdihumboldt.hale.io.haleconnect.ui/src/eu/esdihumboldt/hale/io/haleconnect/ui/projects/ChooseHaleConnectProjectWizardPage.java, io/plugins/eu.esdihumboldt.hale.io.haleconnect.ui/src/eu/esdihumboldt/hale/io/haleconnect/ui/projects/HaleConnectSource.java, io/plugins/eu.esdihumboldt.hale.io.haleconnect.ui/src/eu/esdihumboldt/hale/io/haleconnect/ui/projects/HaleConnectTarget.java, io/plugins/eu.esdihumboldt.hale.io.haleconnect/src/eu/esdihumboldt/hale/io/haleconnect/HaleConnectService.java, io/plugins/eu.esdihumboldt.hale.io.haleconnect/src/eu/esdihumboldt/hale/io/haleconnect/internal/HaleConnectServiceImpl.java, io/plugins/eu.esdihumboldt.hale.io.haleconnect/src/eu/esdihumboldt/hale/io/haleconnect/project/HaleConnectProjectWriter.java
Adds a dropdown box to `HaleConnectTarget` to allow specifying the owner organisation. This prevents unexpected results in case a user has roles in multiple organisations.
In addition, support for logging in again with different credentials is added without forcing the user to clear stored credentials. Previously, in cases where the JWT expires while hale studio is running there was no way to relogin without clearing stored credentials or restarting hale studio.
=> Support multiple organisations in hale connect integration

ui/plugins/eu.esdihumboldt.hale.ui.views.report/src/eu/esdihumboldt/hale/ui/views/report/ReportList.java
Even as with the correct usage of the hale API there shouldn't be reports w/o start time, handling the null case seems to be done in a lot of other places. Thus I added it here as well. Maybe we can use that to identify which I/O provider does not call the `success` method on the report.
=> allow null startTime when comparing reports

common/plugins/eu.esdihumboldt.hale.common.instance/src/eu/esdihumboldt/hale/common/instance/geometry/CRSResolveCache.java, common/plugins/eu.esdihumboldt.hale.common.instance/src/eu/esdihumboldt/hale/common/instance/geometry/impl/EPSGResolveCache.java, io/plugins/eu.esdihumboldt.hale.io.shp/src/eu/esdihumboldt/hale/io/shp/reader/internal/ShapesInstanceCollection.java
There are cases where CRS detection by Geotools is ambiguous when there is no `AUTHORITY` code in the WKT definition of the projection file. To prevent Geotools from silently selecting the wrong CRS, prompt the user in these cases.
=> Prompt user for CRS when projection file does not contain EPSG code

io/plugins/eu.esdihumboldt.hale.io.haleconnect/src/eu/esdihumboldt/hale/io/haleconnect/project/HaleConnectProjectReader.java
This allows `PathUpdate` to correctly resolve relative resource paths (#506).
=> Don't overwrite target of save config when loading from hale connect

io/plugins/eu.esdihumboldt.hale.io.gml.test/src/eu/esdihumboldt/hale/io/gml/writer/internal/StreamGmlWriter2Test.groovy, io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/writer/internal/GmlWriterUtil.java, io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/writer/internal/IndentingXMLStreamWriter.java, io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/writer/internal/PrefixAwareStreamWriter.java, io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/writer/internal/PrefixAwareStreamWriterDecorator.java, io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/writer/internal/StreamGmlWriter.java, io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/writer/internal/XMLStreamWriterDecorator.java
The namespace context after all could not be used to avoid setting duplicate prefixes.
=> fix adding namespace prefixes

common/plugins/eu.esdihumboldt.hale.common.align/src/eu/esdihumboldt/hale/common/align/model/BaseAlignmentCell.java, common/plugins/eu.esdihumboldt.hale.common.align/src/eu/esdihumboldt/hale/common/align/model/Cell.java, common/plugins/eu.esdihumboldt.hale.common.align/src/eu/esdihumboldt/hale/common/align/model/impl/DefaultCell.java, common/plugins/eu.esdihumboldt.hale.common.align/src/eu/esdihumboldt/hale/common/align/model/impl/MutableCellDecorator.java, ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/function/AbstractFunctionWizard.java, ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/function/contribution/internal/ReplaceFunctionWizardAction.java, ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/function/extension/FunctionWizardFactory.java, ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/function/extension/impl/AbstractFunctionWizardDescriptor.java, ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/function/extension/impl/FactoryWizardDescriptor.java, ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/function/generic/AbstractGenericFunctionWizard.java, ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/function/generic/GenericPropertyFunctionWizard.java, ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/function/generic/GenericPropertyFunctionWizardFactory.java, ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/function/generic/GenericTypeFunctionWizard.java, ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/function/generic/GenericTypeFunctionWizardFactory.java
When replacing a `Cell`, copy all annotations of the old `Cell` to the new one. Additionally, pass all existing function parameters of the old `Cell` to the function wizard. All parameters from the old function that are also supported by the new function will the be pre-filled in the wizard.
=> Cell Replace: Preserve annotations and pass existing function parameters to wizard

io/plugins/eu.esdihumboldt.hale.io.gml.ui/src/eu/esdihumboldt/hale/io/gml/ui/GmlReaderSettingsPage.java, io/plugins/eu.esdihumboldt.hale.io.gml/plugin.xml, io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/reader/internal/StreamGmlReader.java, io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/reader/internal/wfs/WfsBackedGmlInstanceCollection.java
One of the RWS WFS reports the number of features returned per request instead of the total number of features. To be able to load all data from that WFS, the value in `numberMatched` must be ignored by hale.
=> Allow to ignore the total number of features reported by a WFS

ui/plugins/eu.esdihumboldt.hale.ui.views.mapping/src/eu/esdihumboldt/hale/ui/views/mapping/MappingView.java
This addresses the problem reported by @JohannaOtt where an `SWTException` (invalid thread access) occurred when `updateLayout` was called by the view's `AlignmentListener`.
=> Fix invalid thread access

common/plugins/eu.esdihumboldt.hale.common.instance/src/eu/esdihumboldt/hale/common/instance/geometry/CRSDefinitionUtil.java, io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/reader/internal/instance/StreamGmlHelper.java, ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/io/instance/crs/SelectCRSDialog.java
- Use guessed EPSG code for .prj file only if axis order is consistent
- Don't prompt user for CRS if resolvable `srsName` is available in GML source
- Add Bursa-Wolf parameter warning to CRS selection dialog if WKT is provided
- Avoid displaying contradicting WKT/codes in CRS selection dialog
- Replace default CRS in selection dialog by ETRS89 (4258)
=> Updates to the CRS selection dialog

cst/plugins/eu.esdihumboldt.cst.functions.core/src/eu/esdihumboldt/cst/functions/core/join/IndexJoinHandler.java, cst/plugins/eu.esdihumboldt.cst.functions.core/src/eu/esdihumboldt/cst/functions/core/merge/IndexMergeHandler.java
The fallback does not affect a transformation's outcome, so this is not critical.
=> Reduce join/merge handler fallback warning to info

io/plugins/eu.esdihumboldt.hale.io.haleconnect.ui/src/eu/esdihumboldt/hale/io/haleconnect/ui/projects/ChooseHaleConnectProjectWizardPage.java
The `instanceof List<?>` check didn't work anymore for the `LinkedHashSet` introduced with #581
=> Fix hale connect project list

common/plugins/eu.esdihumboldt.hale.common.instance.groovy.test/src/eu/esdihumboldt/hale/common/instance/groovy/InstanceAccessorTest.groovy, common/plugins/eu.esdihumboldt.hale.common.instance.groovy/src/eu/esdihumboldt/hale/common/instance/groovy/InstanceAccessor.groovy
@JohannaOtt With this PR you can access all children on a certain level with the instance accessor.
Usage for instance like `instance.p.'*'.street.values()` as in the example in the commit (the asterisk picks up "address", "address2" and "address3").
But you have to be careful as this also picks up groups (e.g. choices). So in your use case I think you have to go down two levels using this.
=> InstanceAccessor: support descending into all children

CHANGELOG.md, common/plugins/eu.esdihumboldt.hale.common.instance/src/eu/esdihumboldt/hale/common/instance/model/ext/impl/PerTypeInstanceCollection.java, common/plugins/eu.esdihumboldt.hale.common.instance/src/eu/esdihumboldt/hale/common/instance/model/impl/SingleTypeInstanceCollection.java, io/plugins/eu.esdihumboldt.hale.io.gml.ui/src/eu/esdihumboldt/hale/io/gml/ui/PartitionConfigurationPage.java, io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/writer/internal/DefaultMultipartHandler.java, io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/writer/internal/LocalReferenceUpdater.java, io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/writer/internal/MultipartHandler.java, io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/writer/internal/PerTypePartsHandler.java, io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/writer/internal/ReferenceUpdater.java, io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/writer/internal/ReferenceUpdatingStreamWriter.java, io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/writer/internal/StreamGmlWriter.java, ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/service/project/RecentProjectsMenu.java
See feature request #564.
This implements the option to split the GML output by feature type. The type name is included in the output file name, e.g. `output.gml` turns into `output.<type name>.gml`. Local references to other types will be updated to relative references, e.g. `#FeatureTypeA_feature1` will turn into `output.FeatureTypeA.gml#FeatureTypeA_feature1` (this does _not_ rely on the feature type name being part of the feature ID).
The feature type split cannot be combined with the partitioning by number of objects.
=> Add partitioning by feature type to GML export

ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/service/project/internal/ProjectServiceImpl.java
Disables the live transformation before the alignment is loaded. With the previous implementation there were cases where the loading of the alignment triggered a retransformation although no source data was loaded yet (#583).
=> Disable live transformation before loading alignment

ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/service/project/internal/ProjectServiceImpl.java
Avoids a possible error in case an I/O provider is not known,
that would prevent loading the project.
@thorsten-reitz Addresses the issue you had this morning. The user then should be able to load the project partially and get a more useful error.
=> identify source data configurations by action ID

common/plugins/eu.esdihumboldt.hale.common.core/src/eu/esdihumboldt/hale/common/core/io/impl/TextType.java
This prevents writing `\r` line endings for `Text` values, e.g. Groovy scripts. 
Although values with a `\r` line ending get de-serialized fine, they prevent effective git diffs because (at least on Windows) the `\r` is not recognized as a line ending by the diff tool and the whole text ends up on a single line.
=> Prevent CR line endings when serializing Text values

io/plugins/eu.esdihumboldt.hale.io.shp.ui/src/eu/esdihumboldt/hale/io/shp/ui/TypeSelectionPage.java, io/plugins/eu.esdihumboldt.hale.io.shp/.classpath, io/plugins/eu.esdihumboldt.hale.io.shp/.settings/org.eclipse.jdt.core.prefs, io/plugins/eu.esdihumboldt.hale.io.shp/META-INF/MANIFEST.MF, io/plugins/eu.esdihumboldt.hale.io.shp/plugin.xml, io/plugins/eu.esdihumboldt.hale.io.shp/src/eu/esdihumboldt/hale/io/shp/ShapefileConstants.java, io/plugins/eu.esdihumboldt.hale.io.shp/src/eu/esdihumboldt/hale/io/shp/reader/internal/ShapeInstanceReader.java, io/plugins/eu.esdihumboldt.hale.io.shp/src/eu/esdihumboldt/hale/io/shp/reader/internal/ShapesInstanceCollection.java
This adds an option to the Shapefile importer to try to match its property names to a target type property by checking if there is exactly one target type property name that starts with the Shapefile property name. 
In case such a property exists (e.g. `beschreibu` in the Shapefile and `beschreibung` in the target type) the source property will be imported to the target property. 
In case of multiple property names in the target type that start with the Shapefile property name, the property will not be imported.
This behaviour is deactivated by default and can be activated by the new Shapefile reader parameter `matchShortPropertyNames`.
=> Allow importing Shapefiles with shortened property names

ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/service/project/internal/ProjectServiceImpl.java
When there are multiple sources, this prevents running transformations after every single source import. This addresses the problem in #644.
=> Disable transformation when sampling causes reloading of sources

platform/hale-platform.target, ui/plugins/eu.esdihumboldt.hale.ui.application/HALE.product
This PR adds to HALE support for remote software updates.
To achieve this, a few features from the [ECF framework](https://www.eclipse.org/ecf/) have been added to HALE's target platform, and the feature `org.eclipse.equinox.p2.core.feature` has been added to `HALE.product`.
Remote updates have been manually tested using a HALE build incorporating the changes in this PR. 
Related forum discussion is [here](https://discuss.wetransform.to/#/thread/i15b/Installing-new-features-from-remote-p2-update-sites).
=> Enable software updates from remote p2 repositories

io/plugins/eu.esdihumboldt.hale.io.haleconnect.ui/src/eu/esdihumboldt/hale/io/haleconnect/ui/internal/HaleConnectUIPlugin.java, io/plugins/eu.esdihumboldt.hale.io.haleconnect.ui/src/eu/esdihumboldt/hale/io/haleconnect/ui/preferences/HaleConnectExtendedPreferencePage.java, io/plugins/eu.esdihumboldt.hale.io.haleconnect.ui/src/eu/esdihumboldt/hale/io/haleconnect/ui/preferences/PreferenceInitializer.java, io/plugins/eu.esdihumboldt.hale.io.haleconnect.ui/src/eu/esdihumboldt/hale/io/haleconnect/ui/projects/ChooseHaleConnectProjectWizardPage.groovy, io/plugins/eu.esdihumboldt.hale.io.haleconnect/src/eu/esdihumboldt/hale/io/haleconnect/BasePathManager.java, io/plugins/eu.esdihumboldt.hale.io.haleconnect/src/eu/esdihumboldt/hale/io/haleconnect/HaleConnectServices.java, io/plugins/eu.esdihumboldt.hale.io.haleconnect/src/eu/esdihumboldt/hale/io/haleconnect/internal/HaleConnectServiceImpl.groovy
Moved the constants for default values from UI components to HaleConnectServices and ensure the
HaleConnectService instance is created with the default settings. Also extended BasePathManager w/
convenience methods for setting a base URL and the default settings.
=> refactor(io): initialize HaleConnectService with default settings

common/plugins/eu.esdihumboldt.hale.common.headless/src/eu/esdihumboldt/hale/common/headless/impl/ProjectTransformationEnvironment.java
Makes the location a project was loaded from available after the creation of a
ProjectTransformationEnvironment.
=> refactor(common): expose project load location in ProjectTransformationEnvironment

ui/plugins/eu.esdihumboldt.hale.ui.views.properties/src/eu/esdihumboldt/hale/ui/views/properties/definition/typedefinition/geometry/TypeSrsCodeFilter.java
This patch prevents a `ClassCastException` in case `input` is a `GroupPropertyDefinition`.
=> fix(ui): Prevent possible ClassCastException in TypeSrsCodeFilter

common/plugins/eu.esdihumboldt.hale.common.schema.persist/src/eu/esdihumboldt/hale/common/schema/persist/hsd/json/JsonToSchema.groovy
Sometimes a constraint in a hale schema definition cannot be recreated, e.g. because the plugin that defines the constraint is unavailable. To allow loading the HSD anyway, the message level is reduced to a warning.
https://github.com/halestudio/hale/issues/707
=> fix(hsd): don't log error if constraint type can't be recreated

common/plugins/eu.esdihumboldt.hale.common.headless/src/eu/esdihumboldt/hale/common/headless/impl/ProjectTransformationEnvironment.java, cst/plugins/eu.esdihumboldt.cst.functions.groovy/src/eu/esdihumboldt/cst/functions/groovy/internal/GroovyUtil.java
The method of storing compiled scripts in the `ExecutionContext` of either the `TransformationFunction` or the `Cell` does not work in the case of inline transformations. If a property is mapped by an inline
transformation, a separate transformer instance is instantiated for every property value. As the `ConceptualSchemaTransformer` itself is stateless, the cached scripts do not get passed on and are recompiled for every property value, causing a significant slowdown (as reported in #575).
This new simple thread-local cache avoids this problem as long as the CSTs for the inline property transformations are all executed within the same thread.
A possible drawback is the increased memory usage as, over the course of a transformation run, every Groovy script will be cached. If this turns out …
=> Inline transformations: Improve caching of Groovy scripts and fix exception when used in CLI

build/gradle/commitAndProductionStage.gradle
Simple approach to add a `HALE.p2.inf` file with the AppSchema plugin update site
https://github.com/halestudio/hale/issues/715
=> build: include AppSchema plugin update site by default

io/plugins/eu.esdihumboldt.hale.io.haleconnect.ui/src/eu/esdihumboldt/hale/io/haleconnect/ui/projects/ShareProjectWizard.java, io/plugins/eu.esdihumboldt.hale.io.haleconnect/src/eu/esdihumboldt/hale/io/haleconnect/project/HaleConnectProjectWriter.groovy
When exporting a project to hale connect, the resource URIs in the `IOConfiguration` would point to the temporary location where the project archive for the hc upload was assembled. These temporary paths would then be persisted if the project was subsequently saved locally. It would also lose all source data configurations if the hc upload did not contain source data.
This patch prevents this by restoring the `IOConfiguration`s if the project is exported to hale connect (i.e. `HaleConnectProjectWriter` is run in `EXPORT` mode).
#642
=> fix(io): prevent bad IOConfiguration paths after hale connect export

common/plugins/eu.esdihumboldt.hale.common.headless/src/eu/esdihumboldt/hale/common/headless/transform/Transformation.java
With this patch not-inserted instances are also filtered out if the matched object is decorated. This is the case e.g. when the instance was created by an `InlineTransformation`. Such instances were not filtered out before and were written twice in GML serialization.
#575
=> fix(headless): also filter OInstances when object to match is decorated

io/plugins/eu.esdihumboldt.hale.io.haleconnect.ui/src/eu/esdihumboldt/hale/io/haleconnect/ui/projects/HaleConnectProjectExportAdvisor.java, io/plugins/eu.esdihumboldt.hale.io.haleconnect/src/eu/esdihumboldt/hale/io/haleconnect/project/HaleConnectProjectWriter.groovy
This partially reverts the previous commit on this matter and instead changes the export advisor to use a clone of project to prevent inadvertent changes to the project's `IOConfiguration`s on exports.
#642
=> fixup! fix(io): prevent bad IOConfiguration paths after hale connect export

common/plugins/eu.esdihumboldt.hale.common.core.test/src/eu/esdihumboldt/hale/common/core/io/project/util/XMLPathUpdaterTest.java, common/plugins/eu.esdihumboldt.hale.common.core/src/eu/esdihumboldt/hale/common/core/io/project/util/XMLPathUpdater.java
Refactored the code in XMLPathUpdater in a way that an input stream is
only acquired in case the data is intended to be read and the stream is
ensured to be closed.
=> fix: fix possible deadlock when copying XML schemas w/ complete dependencies

common/plugins/eu.esdihumboldt.hale.common.instance.index/src/eu/esdihumboldt/hale/common/instance/index/InstanceIndexUtil.java, cst/plugins/eu.esdihumboldt.cst.test/src/eu/esdihumboldt/cst/internal/ConceptualSchemaTransformerTest.java, cst/plugins/eu.esdihumboldt.cst.test/src/eu/esdihumboldt/cst/test/TransformationExamples.groovy, cst/plugins/eu.esdihumboldt.cst.test/src/testdata/propjoin_int_float/instance1.xml, cst/plugins/eu.esdihumboldt.cst.test/src/testdata/propjoin_int_float/instance2.xml, cst/plugins/eu.esdihumboldt.cst.test/src/testdata/propjoin_int_float/t1.xsd, cst/plugins/eu.esdihumboldt.cst.test/src/testdata/propjoin_int_float/t1t2.halex, cst/plugins/eu.esdihumboldt.cst.test/src/testdata/propjoin_int_float/t1t2.halex.alignment.xml, cst/plugins/eu.esdihumboldt.cst.test/src/testdata/propjoin_int_float/t1t2.halex.styles.sld, cst/plugins/eu.esdihumboldt.cst.test/src/testdata/propjoin_int_float/t2.xsd
This patch adds the same behaviour to the processing of double and
float values that already existed for BigDecimals. In particular,
double and float values that are in fact integers (e.g. `2.0`) are
now serialized without the trailing `.0` during value processing.
This allows the mixed use of float/double and integer/string properties
in Joins.
https://github.com/halestudio/hale/issues/737
=> Support joins of float and integer properties

io/plugins/eu.esdihumboldt.hale.io.groovy/src/eu/esdihumboldt/hale/io/groovy/snippets/impl/SnippetServiceImpl.java
In a headless environment the GroovyService may not be available. This
should not lead to an error as it is only needed to react to restriction
changes, which usually don't occur in a headless environment.
=> fix: prevent possible NPE in SnippetServiceImpl

io/plugins/eu.esdihumboldt.hale.io.deegree.ui/src/eu/esdihumboldt/hale/io/deegree/ui/BasicMappingConfigurationPage.java, io/plugins/eu.esdihumboldt.hale.io.deegree/src/eu/esdihumboldt/hale/io/deegree/mapping/MappingWriter.java, io/plugins/eu.esdihumboldt.hale.io.deegree/src/eu/esdihumboldt/hale/io/deegree/mapping/config/GenericMappingConfiguration.java, io/plugins/eu.esdihumboldt.hale.io.deegree/src/eu/esdihumboldt/hale/io/deegree/mapping/config/MappingConfiguration.java, io/plugins/eu.esdihumboldt.hale.io.deegree/src/eu/esdihumboldt/hale/io/deegree/mapping/model/MappedAppSchemaCopy.java
This adds two new options to the deegree configuration exporter, allowing to include both abstract types and feature types that deegree identifies as feature collections to the generated mapping.
Including feature collections is sometimes necessary when deegree falsely identifies a feature type as a feature collection (happens e.g. for `OM_Observation`).
SVC-310
=> Add options to include feature collections and abstract types in deegree config export

common/plugins/eu.esdihumboldt.hale.common.core/src/eu/esdihumboldt/hale/common/core/io/PathUpdate.java
Adds MongoDB URI schema support on PathUpdate class, same as JDBC scheme.
Related issue:
https://github.com/halestudio/hale/issues/762
=> #762 Add support for MongoDB URI scheme

build/build.gradle
This replaces the bundled Oracle JREs with OpenJDK JREs built by
AdoptOpenJDK:
https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/tag/jdk8u232-b09
Since there is currently no 32-bit OpenJDK build for Linux available
from AdoptOpenJDK, no JRE will be bundled with 32-bit Linux builds
anymore.
The corresponding update to `hale-build-support` was done in this
commit:
https://gitlab.wetransform.to/hale/hale-build-support/commit/6589f561a36b8a6fe4cd6a115fdc892bbf812c68
https://github.com/halestudio/hale/issues/758
=> build: use OpenJDK binaries instead of Oracle ones

io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/reader/internal/instance/GroupUtil.java
This fixes the check whether a group may be closed. If a group is not closed although it would be ok to do so, hale will try to find subsequently read properties in that group instead of the parent.
https://github.com/halestudio/hale/issues/764
=> fix: fix property determination in case a group is present

io/plugins/eu.esdihumboldt.hale.io.haleconnect.ui/src/eu/esdihumboldt/hale/io/haleconnect/ui/projects/ChooseHaleConnectProjectWizardPage.groovy, io/plugins/eu.esdihumboldt.hale.io.haleconnect.ui/src/eu/esdihumboldt/hale/io/haleconnect/ui/projects/HaleConnectTarget.java, io/plugins/eu.esdihumboldt.hale.io.haleconnect/src/eu/esdihumboldt/hale/io/haleconnect/HaleConnectOrganisationInfo.groovy, io/plugins/eu.esdihumboldt.hale.io.haleconnect/src/eu/esdihumboldt/hale/io/haleconnect/HaleConnectProjectInfo.groovy, io/plugins/eu.esdihumboldt.hale.io.haleconnect/src/eu/esdihumboldt/hale/io/haleconnect/HaleConnectUserInfo.groovy, io/plugins/eu.esdihumboldt.hale.io.haleconnect/src/eu/esdihumboldt/hale/io/haleconnect/internal/HaleConnectServiceImpl.groovy
This adds handling for cases where user or organisation info is queried via the hale connect API, but the information is cannot be obtained (e.g. because the user/org was deleted in the meantime or because of missing authorization).
Previously, failure to retrieve user/org information could lead to errors in the UI.
https://github.com/halestudio/hale/issues/752
=> fix(hc): handle cases where user/org information is unavailable

io/plugins/eu.esdihumboldt.hale.io.jdbc.postgresql.test/src/eu/esdihumboldt/hale/io/jdbc/postgresql/test/MultiDimensionalArraysIT.groovy, io/plugins/eu.esdihumboldt.hale.io.jdbc.postgresql.test/src/eu/esdihumboldt/hale/io/jdbc/postgresql/test/OneDimensionalArraysIT.groovy, io/plugins/eu.esdihumboldt.hale.io.jdbc.postgresql.test/src/eu/esdihumboldt/hale/io/jdbc/postgresql/test/PostDataTypesIT.groovy
PR https://github.com/halestudio/hale/pull/787 appears to have broken the PostgreSQL integration tests. This adds binding checks for `BIGSERIAL`  and `TEXT` data types.
Examples for failing builds:
https://builds.wetransform.to/job/hale/job/hale%7Epublish(master)/480/console
https://builds.wetransform.to/job/hale/job/hale%7Ebuild(staging)/27/console
=> Fix PostgreSQL integration tests

io/plugins/eu.esdihumboldt.hale.io.geopackage/src/eu/esdihumboldt/hale/io/geopackage/internal/GeopackageFeatureCollection.java
This replaces the "chunked" read approach of the initial implementation with a "fetch everything" approach.
Calling `queryForChunk` and `features.count()` often versus calling `queryForAll` once comes with a significant performance penalty.
Caching `features.count()` cut the load time roughly by a third compared to the original approach.
By switching to `queryForAll`I was able to reduce the time required to read 10k features (5 types with 2000 features each) on my machine from 188 seconds to 36 seconds.
https://github.com/halestudio/hale/issues/795
=> perf: improve GeoPackage reader performance

io/plugins/eu.esdihumboldt.hale.io.haleconnect/src/eu/esdihumboldt/hale/io/haleconnect/internal/ApiClientHelper.groovy, io/plugins/eu.esdihumboldt.hale.io.haleconnect/src/eu/esdihumboldt/hale/io/haleconnect/internal/BucketServiceHelper.java, io/plugins/eu.esdihumboldt.hale.io.haleconnect/src/eu/esdihumboldt/hale/io/haleconnect/internal/ProjectServiceHelper.java, io/plugins/eu.esdihumboldt.hale.io.haleconnect/src/eu/esdihumboldt/hale/io/haleconnect/internal/ProjectStoreHelper.java, io/plugins/eu.esdihumboldt.hale.io.haleconnect/src/eu/esdihumboldt/hale/io/haleconnect/internal/UserServiceHelper.groovy
This limits the supported TLS version to v1.2 and the available cipher suites to
those that have perfect forward security (PFS) for all hale connect API
connections.
This also fixes the problem where hale studio / hale-cli were unable to connect
to deployments that have a strict SSL policy and support TLS 1.2/1.3 with
selected cipher suites only.
https://github.com/halestudio/hale/issues/758
=> fix(hc-api): fix connection problem when endpoint supports TLS 1.2 only

common/plugins/eu.esdihumboldt.hale.common.headless/src/eu/esdihumboldt/hale/common/headless/transform/LimboInstanceSink.java
Not sure why this was not implemented before - it should be OK just
retrieving specific instances, even if it is not possible to iterate
over the collection more than once. This just means that there might be
instances coming out of the transformation that are not
handled/exported.
The previous behavior would prevent instance to be written with a CSV or
Excel writer in case the LimboInstanceSink was used, as it only processes
instances of a specific type (depending on configuration).
=> fix: allow filtering LimboInstanceSink instance collection

cst/plugins/eu.esdihumboldt.cst.functions.groovy.helpers/plugin.xml, cst/plugins/eu.esdihumboldt.cst.functions.groovy.helpers/src/eu/esdihumboldt/cst/functions/groovy/helpers/JsonHelpers.groovy
As the JsonSlurper class was not whitelisted and should not (as it has
broad access to the file system), a wrapper function is created for it.
=> feat: add helper function to parse JSON data

io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/internal/simpletype/SimpleTypeUtil.java
Make sure that leading and trailing whitespace is removed before splitting
the value of an element bound to `java.util.List` at whitespace.
The old behaviour lead to three list entries (an empty one followed by the one
for each of the actual values) being created for the `pos` element value from
the following snippet:
```
<gml:Point srsName="EPSG:25832" gml:id="GML-f">
<gml:pos>
540465.8278 5802259.4572
</gml:pos>
</gml:Point>
```
However, the snippet above should have the same semantics as
```
<gml:Point srsName="EPSG:25832" gml:id="GML-f">
<gml:pos>540465.8278 5802259.4572</gml:pos>
</gml:Point>
```
Therefore, leading and trailing whitespace is now removed before the split.
https://github.com/halestudio/hale/issues/808
Thanks @JohannaOtt for reporting the bug and helping find a fix.
=> fix(io): List binding: trim whitespace before splitting

build/gradle/deployArtifacts.gradle
Updates the repository URL needed to validate artifacts.
https://github.com/halestudio/hale/issues/821
=> build: fix URL of OSGeo repository

platform/hale-platform.target, ui/plugins/eu.esdihumboldt.hale.ui.application/plugin.xml
Updates the target platform to the latest version that contains the XPlanGML. Also updates the splash copyright notice to 2020.
=> Add XPlanGML schema presets

io/plugins/eu.esdihumboldt.hale.io.gml.ui/plugin.xml, io/plugins/eu.esdihumboldt.hale.io.gml.ui/src/eu/esdihumboldt/hale/io/gml/ui/XPlanGmlWriterSettingsPage.java, io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/writer/XPlanGmlInstanceWriter.java, io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/writer/internal/StreamGmlWriter.java
Adds a partitioning scheme for the XPlanGML writer that writes all instances of
`*_PlanType` and their directly or indirectly referenced non-plan instances
into separate output files. The name of the output files contains both the
type and the ID of the exported plan.
The split is achieved by first separating plan instances into different
`InstanceCollections` and then, for each plan, adding all referenced
instances found in the reference graph. This might result in instances
being written multiple times if they are shared between different plans.
=> feat: support partitioning XPlanGML by plan

util/plugins/eu.esdihumboldt.util.groovy.sandbox/src/eu/esdihumboldt/util/groovy/sandbox/DefaultGroovyService.java, util/plugins/eu.esdihumboldt.util.groovy.sandbox/src/eu/esdihumboldt/util/groovy/sandbox/GroovyService.java
Groovy scripts created with pre-4.0 hale studio releases that explicitly use
classes from JTS fail to compile after the upgrade of GeoTools as the
base package name changed from `com.vividsolutions.jts` to
`org.locationtech.jts`.
This adds a transparent replacement of occurrences of the old base package name
by the new one.
https://github.com/halestudio/hale/issues/821
=> feat: transparently replace old JTS package name in Groovy scripts

build/build.gradle
The reachability of the GitLab instance is currently shaky. Switch to S3 mirror temporarily to allow builds.
=> build: temporarily use build-artifacts mirror instead of GitLab

io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/internal/simpletype/SimpleTypeUtil.java
Prevents that time zone information is added to the GML output when
writing an `xmlDate`. Before, a date-only target property would
get serialized as e.g.
<xplan:genehmigungsDatum>2020-08-02+02:00</xplan:genehmigungsDatum>
with the actual time zone suffix `+02:00` depending on the system time zone.
With this fix, the above example gets serialized as
<xplan:genehmigungsDatum>2020-08-02</xplan:genehmigungsDatum>
instead.
https://github.com/halestudio/hale/issues/316
=> fix: don't append time zone information when writing xmlDate

common/plugins/eu.esdihumboldt.hale.common.schema/src/eu/esdihumboldt/hale/common/schema/model/constraint/type/factory/GeometryTypeFactory.java
As part of the upgrade to GeoTools 21, a wrong bundle name was used as the
preferred bundle when loading geometry types. The wrong bundle name causes
significant delays when loading schemas with geometries as hale tried to
locate the non-existing bundle for every geometry element in the schema.
The correct bundle name is `org.locationtech.jts.jts-core`. In addition,
replacing the old GeoTools package name in the class name is now done
before trying to load geometry class.
https://github.com/halestudio/hale/issues/861
=> fix: use correct preferred bundle when loading geometry types

util/plugins/eu.esdihumboldt.util.groovy.sandbox/src/eu/esdihumboldt/util/groovy/sandbox/internal/RestrictiveGroovyInterceptor.java
Adds several classes of the `java.time` package to the list of allowed classes that are not restricted.
=> feat: allow usage of Java 8 date/time classes in Groovy

io/plugins/eu.esdihumboldt.hale.io.gml.ui/src/eu/esdihumboldt/hale/io/gml/ui/GmlWriterSettingsPage.java
Check the option `Pretty print XML` by default in the writer settings dialog page when exporting XML/GML.
=> refactor(ui): activate XML pretty printing by default

io/plugins/eu.esdihumboldt.hale.io.geopackage.test/src/eu/esdihumboldt/hale/io/geopackage/GeopackageInstanceWriterTest.groovy, io/plugins/eu.esdihumboldt.hale.io.geopackage.ui/META-INF/MANIFEST.MF, io/plugins/eu.esdihumboldt.hale.io.geopackage.ui/plugin.xml, io/plugins/eu.esdihumboldt.hale.io.geopackage.ui/src/eu/esdihumboldt/hale/io/geopackage/ui/GeopackageWriterSettingsPage.java, io/plugins/eu.esdihumboldt.hale.io.geopackage/plugin.xml, io/plugins/eu.esdihumboldt.hale.io.geopackage/src/eu/esdihumboldt/hale/io/geopackage/GeopackageInstanceWriter.java, io/plugins/eu.esdihumboldt.hale.io.geopackage/src/eu/esdihumboldt/hale/io/geopackage/GeopackageSpatialIndexType.java
Add support for creating spatial indexes and create an RTree spatial index by default when creating new GeoPackage files.
refs #883
=> Support creating a spatial index when writing GeoPackage files

common/plugins/eu.esdihumboldt.hale.common.convert.core/src/eu/esdihumboldt/hale/common/convert/core/StringToInstantConverter.java
When a timestamp string that is to be converted to java.time.Instant
causes a `DateTimeParseExcpetion`, try to reparse it with an added `Z`.
This allows to be lenient about ISO 8601 timestamps from GeoPackages that
are missing the time zone information.
https://github.com/halestudio/hale/issues/887
=> feat: be lenient about missing time zone information when parsing timestamps

.travis.yml
Log into Docker Hub before starting  a product build to prevent hitting [rate limits](https://docs.docker.com/docker-hub/download-rate-limit/) for anonymous users.
=> build: login to Docker Hub before building products

io/plugins/eu.esdihumboldt.hale.io.gml.geometry.test/src/data/arcstring/sample-arcstring-gml32.xml, io/plugins/eu.esdihumboldt.hale.io.gml.geometry.test/src/data/gml/geom-gml32.xsd, io/plugins/eu.esdihumboldt.hale.io.gml.geometry.test/src/eu/esdihumboldt/hale/io/gml/geometry/handler/ArcStringHandlerTest.java, io/plugins/eu.esdihumboldt.hale.io.gml.geometry.test/src/eu/esdihumboldt/hale/io/gml/geometry/handler/internal/AbstractHandlerTest.java, io/plugins/eu.esdihumboldt.hale.io.gml.geometry/src/eu/esdihumboldt/hale/io/gml/geometry/handler/ArcStringHandler.java
When an ArcString object was devided in single Arc objects in order to
interpolate them before, the iterator was raised by 3 in every step. As
gml:ArcString objects consist of multiple arcs object and the endpoint
of one arc represents the start point of the next arc at the same time.
This means, if two arcs are contained in an ArcString object, the first
arc starts as coordinate 0 and the second one starts at coordinate 2 etc.
So the iterator for the starting point should only be raised by 2 in order
to access the next arc.
WGS-1215
=> fix: fix ArcString interpolation handling

cst/plugins/eu.esdihumboldt.cst.functions.geometric/build.properties
Add `help/` folder created in 3b43b45c899e0d8f59fa673b483ae8da591b8b72 to binary build
=> fixup! docs:Added function examples

.travis.yml, io/plugins/eu.esdihumboldt.hale.io.xsd/src/eu/esdihumboldt/hale/io/xsd/reader/XmlSchemaReader.java
Patch to prevent duplicate import of the same schema when the schema locations differ only in the scheme part, e.g. `http://example.org/a.xsd` and `https://example.org/a.xsd`.
Also fix up the Travis CI build to also log into Docker when running the integration stage.
=> Prevent duplicate imports of the same schema

ui/plugins/eu.esdihumboldt.hale.ui.util/META-INF/MANIFEST.MF, ui/plugins/eu.esdihumboldt.hale.ui.util/src/eu/esdihumboldt/hale/ui/util/proxy/ProxySettings.java, ui/plugins/eu.esdihumboldt.hale.ui.util/src/eu/esdihumboldt/hale/ui/util/proxy/preferences/ProxyPreferencePage.java
Replaces the direct setting of proxy-related system properties by calls to the
proxy interface exposed by the Eclipse `IProxyService`.
This also allows the proxy settings to be applied to RCP components that are
used within hale»studio, like the software installation dialog to install
plugins.
https://github.com/halestudio/hale/issues/727
SVC-881
=> fix(ui): use IProxyService to apply proxy configuration in the UI

ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/io/schema/SourceSchemaActionUIAdvisor.java, ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/io/schema/TargetSchemaActionUIAdvisor.java
This commit provides a fix to delete a single schema
when an alignment project is loaded.
ING-2968
=> fixup! feat:Remove single schema from project view

common/plugins/eu.esdihumboldt.hale.common.test/Tests.product, util/features/eu.esdihumboldt.util.feature.resource/feature.xml, util/plugins/eu.esdihumboldt.util.resource.schemas.end/.project, util/plugins/eu.esdihumboldt.util.resource.schemas.end/.settings/org.eclipse.jdt.core.prefs, util/plugins/eu.esdihumboldt.util.resource.schemas.end/META-INF/MANIFEST.MF, util/plugins/eu.esdihumboldt.util.resource.schemas.end/build.properties, util/plugins/eu.esdihumboldt.util.resource.schemas.end/plugin.xml
This commit provides support for
adding END related schemas to
the presets tab for source and target
schemas.
The schemas are directly used from
the GitHub urls.
ING 2970
=> feat: add END-related schemas to presets

common/plugins/eu.esdihumboldt.hale.common.core/src/eu/esdihumboldt/hale/common/core/io/ImportProvider.java, common/plugins/eu.esdihumboldt.hale.common.core/src/eu/esdihumboldt/hale/common/core/io/impl/AbstractImportProvider.java, common/plugins/eu.esdihumboldt.hale.common.core/src/eu/esdihumboldt/hale/common/core/io/supplier/FilesIOSupplier.java, io/plugins/eu.esdihumboldt.hale.io.jdbc.spatialite/src/eu/esdihumboldt/hale/io/jdbc/spatialite/reader/internal/SpatiaLiteInstanceReader.java, io/plugins/eu.esdihumboldt.hale.io.jdbc.spatialite/src/eu/esdihumboldt/hale/io/jdbc/spatialite/reader/internal/SpatiaLiteSchemaReader.java, io/plugins/eu.esdihumboldt.hale.io.shp.ui/src/eu/esdihumboldt/hale/io/shp/ui/TypeSelectionPage.java, io/plugins/eu.esdihumboldt.hale.io.shp/src/eu/esdihumboldt/hale/io/shp/ShapefileConstants.java, io/plugins/eu.esdihumboldt.hale.io.shp/src/eu/esdihumboldt/hale/io/shp/reader/internal/ShapeInstanceReader.java, ui/plugins/eu.esdihumboldt.hale.ui.util/src/eu/esdihumboldt/hale/ui/util/io/ExtendedFileFieldEditor.java, ui/plugins/eu.esdihumboldt.hale.ui.util/src/eu/esdihumboldt/hale/ui/util/io/OpenFileFieldEditor.java, ui/plugins/eu.esdihumboldt.hale.ui/plugin.xml, ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/io/IOWizard.java, ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/io/source/AbstractMultipleFilesSource.java, ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/io/source/AbstractMultipleFilesSourceFileFieldEditor.java, ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/io/source/MultipleInstanceFilesSource.java, ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/io/source/MultipleInstanceFilesSourceFileFieldEditor.java, ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/io/source/MultipleSchemaFilesSource.java, ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/io/source/MultipleSchemaFilesSourceFileFieldEditor.java, ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/service/schema/internal/AbstractSchemaService.java
This commit adds functionality to import multiple source
files for schema import and also enables to import several
data files for the source data import.
It provides some restriction like all the selected files
should be of same format (e.g. all .shp) and does not
allow the selection of multiple csv and xml files for
schema import. However, the user can select multiple
files of same format for source data import.
This also adds auto detect functionality for importing
multiple shape files for multiple shape schemas.
=> feat: enable selecting more than one file when loading schema or data

ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/io/IOWizard.java, ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/io/source/AbstractMultipleFilesSourceFileFieldEditor.java, ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/io/source/FileSourceFileFieldEditor.java
Code provides fix to handle NPE when relative path
check box is selected during the schema/instance
import. Code is modified to fire an explicit state
changed event when relative path check box is
selected.
ING-2969
=> fix: import wizard relative path selection throws NPE

cst/plugins/eu.esdihumboldt.cst.functions.string/plugin.xml, cst/plugins/eu.esdihumboldt.cst.functions.string/src/eu/esdihumboldt/cst/functions/string/DateExtraction.java, cst/plugins/eu.esdihumboldt.cst.functions.string/src/eu/esdihumboldt/cst/functions/string/DateExtractionFunction.java
This commit adds the option of specifying whether or not date/time parsing is to be lenient when using the function DateExtraction. It also modifies the description of the parameter "Date format" so as to be less prone to mistakes (e.g., quotes should not be used and the format refers to the one in the source data).
ING-3214
=> feat: add option to specify leniency when using DateExtraction

io/plugins/eu.esdihumboldt.hale.io.geopackage/plugin.xml, io/plugins/eu.esdihumboldt.hale.io.geopackage/src/eu/esdihumboldt/hale/io/geopackage/GeopackageInstanceReader.java, io/plugins/eu.esdihumboldt.hale.io.geopackage/src/eu/esdihumboldt/hale/io/geopackage/GeopackageSchemaReader.java
Previously, loading a Geopackage would only work if the file has a
`.gpkg` or `.gpkx` extension.
ING-2671
Also: fix(geopackage): queryFilter is a parameter for the reader
=> fix(geopackage): allow loading Geopackage files w/ non standard file extension

build/buildSrc/build.gradle, build/gradle/deployArtifacts.gradle, common/plugins/eu.esdihumboldt.hale.common.schema.persist/src/eu/esdihumboldt/hale/common/schema/persist/hsd/HaleSchemaWriter.java, common/plugins/eu.esdihumboldt.hale.common.schema.persist/src/eu/esdihumboldt/hale/common/schema/persist/hsd/MergeSchemas.java, common/plugins/eu.esdihumboldt.hale.common.schema.persist/src/eu/esdihumboldt/hale/common/schema/persist/hsd/json/HaleSchemaWriterJson.java
When exporting multiple schemas to HSD as XML or Json, merge any schemas
to one schema.
This works around the restriction, that only a single schema can be
imported from an HSD file.
=> refactor: merge schemas for HSD export

common/plugins/eu.esdihumboldt.hale.common.schema/src/eu/esdihumboldt/hale/common/schema/model/constraint/type/IgnoreOrderFlag.java, io/plugins/eu.esdihumboldt.hale.io.gml.test/src/data/allgroup/allgroup.xml, io/plugins/eu.esdihumboldt.hale.io.gml.test/src/data/allgroup/allgroup.xsd, io/plugins/eu.esdihumboldt.hale.io.gml.test/src/eu/esdihumboldt/hale/io/gml/reader/internal/GmlInstanceCollectionTest.java, io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/reader/internal/instance/GroupUtil.java, io/plugins/eu.esdihumboldt.hale.io.xsd.test/src/eu/esdihumboldt/hale/io/xsd/reader/XmlSchemaReaderTest.java, io/plugins/eu.esdihumboldt.hale.io.xsd.test/src/testdata/definitive/allgroup.xsd, io/plugins/eu.esdihumboldt.hale.io.xsd/src/eu/esdihumboldt/hale/io/xsd/reader/XmlSchemaReader.java
Add support for <xs:all> in addition to <xs:choice> and <xs:sequence> in the XML schema reader (see #467). This PR replaces #624.
Changed the implementation to use a type-based constraint rather than a group-based constraint b/c in most practical cases the `<xs:all>` group will be removed and the constraint won't be available.
=> Support XSD types with <xs:all>

ui/plugins/eu.esdihumboldt.hale.ui.functions.groovy/src/eu/esdihumboldt/hale/ui/functions/groovy/internal/JoinTypeStructureTray.java, ui/plugins/eu.esdihumboldt.hale.ui.functions.groovy/src/eu/esdihumboldt/hale/ui/functions/groovy/internal/TypeStructureTray.java
When using the help wizard during a Groovy Merge to specify a Groovy script (to build a target instance from a merged source), the access variable from the source structure automatically proposes to access one single value or all values in a list.
ING-3488
=> Groovy Merge UI: one single variable or a list is proposed

common/plugins/eu.esdihumboldt.hale.common.align/plugin.xml, common/plugins/eu.esdihumboldt.hale.common.align/src/eu/esdihumboldt/hale/common/align/model/functions/RetypeFunction.java, common/plugins/eu.esdihumboldt.hale.common.core/src/eu/esdihumboldt/hale/common/core/parameter/QNameParameterValueDescriptor.java, cst/plugins/eu.esdihumboldt.cst.functions.core/src/eu/esdihumboldt/cst/functions/core/Rename.java, cst/plugins/eu.esdihumboldt.cst.functions.core/src/eu/esdihumboldt/cst/functions/core/Retype.java, ui/plugins/eu.esdihumboldt.hale.ui.functions.core/plugin.xml, ui/plugins/eu.esdihumboldt.hale.ui.functions.core/src/eu/esdihumboldt/hale/ui/functions/core/RetypeSkipPropertiesParameterPage.java
When using Retype with enabled structural rename you can mark
properties to exclude, that will not be copied.
Limitations:
- the UI page for configuring the properties to exclude shows up
regardless if structural rename is enabled or not
- as per design only root properties at the first level in the source
type can be excluded
=> feat: allow excluding root properties from structural Retype

util/plugins/eu.esdihumboldt.util.groovy.sandbox/src/eu/esdihumboldt/util/groovy/sandbox/internal/RestrictiveGroovyInterceptor.java
Currently, it is not possible to add the message of an exception to the transformation's logs as the class is not whitelisted
SVC-1190
=> feat: add Throwable class to whitelist

build/templates/products/client.yaml, ui/plugins/eu.esdihumboldt.hale.ui.application/HALE.product
With the previous `--add-exports`, the build process would generate the following segment in HALE.ini:
```
--add-exports
java.base/sun.nio.ch=ALL-UNNAMED
java.base/jdk.internal.ref=ALL-UNNAMED
```
This leads to hale»studio being unstartable at least on Linux where it gives the following exception:
```
$ ./HALE
Error: Could not find or load main class java.base.jdk.internal.ref=ALL-UNNAMED
Caused by: java.lang.ClassNotFoundException: java.base.jdk.internal.ref=ALL-UNNAMED
```
With the `--add-exports=` notation, the following segment in HALE.ini is generated instead which allows hale»studio to start correctly:
```
--add-exports=java.base/sun.nio.ch=ALL-UNNAMED
--add-exports=java.base/jdk.internal.ref=ALL-UNNAMED
```
ING-3267
=> build: Use --add-exports= to prevent malformed HALE.ini

io/plugins/eu.esdihumboldt.hale.io.geopackage.ui/src/eu/esdihumboldt/hale/io/geopackage/ui/GeopackageWriterSettingsPage.java, io/plugins/eu.esdihumboldt.hale.io.geopackage/plugin.xml, io/plugins/eu.esdihumboldt.hale.io.geopackage/src/eu/esdihumboldt/hale/io/geopackage/GeopackageInstanceWriter.java
Adds two parameters to the GeoPackage writer that
- allows creating tables for all mapping-relevant target types, even if they have no instances
- allow to overwrite the target file if it exists
WGS-2281
#988
=> Enhancements for the GeoPackage writer

io/plugins/eu.esdihumboldt.hale.io.geopackage.ui/src/eu/esdihumboldt/hale/io/geopackage/ui/GeopackageWriterSettingsPage.java, io/plugins/eu.esdihumboldt.hale.io.geopackage/plugin.xml, io/plugins/eu.esdihumboldt.hale.io.geopackage/src/eu/esdihumboldt/hale/io/geopackage/GeopackageInstanceWriter.java
Backport the change to allow creation of empty tables in GeoPackages from [this PR](https://github.com/halestudio/hale/pull/1027) to the 4.x branch so that it becomes available for hale»connect transformations.
=> Backport GeoPackage empty table creation to 4.x

build/templates/pom-parent.xml
groovy-jfrog.io artifactory no longer contains jar: org.osgi:org.osgi.service.prefs:jar:1.1.2, so priority list of pluginRepositories is now changed to include maven central on top
=> build: change priority list of pluginRepositories

io/plugins/eu.esdihumboldt.hale.io.shp.test/src/eu/esdihumboldt/hale/io/shp/ShapefileInstanceWriterTest.groovy
The new PR contains the update with the missing import that makes the following PR failing:
Reference old failed PR: https://github.com/halestudio/hale/pull/1036
=> Update feat_maint_4.x: extend shapefile writer to create .cpg file

CHANGELOG.md, RELEASE.md, build/ant/build-msi.xml, build/config.groovy, build/gradle/commitAndProductionStage.gradle
The following changes have been done to solve the windows installer build error:
- add encoding UTF-8 to all the replace into file
- add more details in how to create the windows installer
- update GUID used for shortcuts.
ING-3831
=> Build: windows installer fixes

io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/reader/internal/wfs/WfsBackedGmlInstanceCollection.java
Refactor to rename downloaded file to not start with a "." and to have name format as
<datasetId>_<numberOfTotalFeatureProcessed>
ING-3609
=> fixup! feat: download wfs files to tmp folder for bucket service

io/plugins/eu.esdihumboldt.hale.io.csv.ui/src/eu/esdihumboldt/hale/io/csv/ui/InstanceExportConfigurationPage.java, io/plugins/eu.esdihumboldt.hale.io.csv/src/eu/esdihumboldt/hale/io/csv/InstanceTableIOConstants.java, io/plugins/eu.esdihumboldt.hale.io.xls.test/src/eu/esdihumboldt/hale/io/xls/test/XLSInstanceIOTest.java, io/plugins/eu.esdihumboldt.hale.io.xls.test/src/eu/esdihumboldt/hale/io/xls/test/writer/XLSInstanceWriterTest.java, io/plugins/eu.esdihumboldt.hale.io.xls.ui/src/eu/esdihumboldt/hale/io/xls/ui/XLSInstanceExportConfigurationPage.java, io/plugins/eu.esdihumboldt.hale.io.xls/src/eu/esdihumboldt/hale/io/xls/writer/XLSInstanceWriter.java
CSV: Add a warning label to CSV dialog telling that feature types without data are not selectable.
XSL: remove the button "Ignore feature types without data" and add intro the checkbox table disabled from selection elements that don't have any data for export.
ING-3987
=> feat: type selection broken on custom export config

io/plugins/eu.esdihumboldt.hale.io.xls.ui/src/eu/esdihumboldt/hale/io/xls/ui/XLSInstanceExportConfigurationPage.java
Align the XSL and CSV by getting the selected elements of the CheckboxTableViewer and removing the greyed out elements that cannot be selected. The grey elements are not used later because they don't have any properties, but better to send the complete and right list of selected elements.
related ING-3941
=> fixup: align XSL with CSV by getting the selected elements without grey elements

io/plugins/eu.esdihumboldt.hale.io.shp.test/src/eu/esdihumboldt/hale/io/shp/ShapefileInstanceWriterTest.groovy, io/plugins/eu.esdihumboldt.hale.io.shp/src/eu/esdihumboldt/hale/io/shp/writer/ShapefileInstanceWriter.java, ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/io/config/SimpleTargetCRSConfigurationPage.java
Shapefile files are correctly generated by the sending the CRS to the Geometry Finder.
ING-3974
=> fixup! fix: For Shapefile writer recognize geometries for feature types

io/plugins/eu.esdihumboldt.hale.io.shp.test/src/eu/esdihumboldt/hale/io/shp/ShapefileInstanceWriterTest.groovy, io/plugins/eu.esdihumboldt.hale.io.shp/src/eu/esdihumboldt/hale/io/shp/writer/ShapefileInstanceWriter.java
No shift in the attributes happens when exporting a transformed data to shp-file.
ING-4052
=> fix: export transformed data leads to a shift of the attribute values

common/plugins/eu.esdihumboldt.hale.common.core/src/eu/esdihumboldt/hale/common/core/report/SimpleLog.java, io/plugins/eu.esdihumboldt.hale.io.json.test/src/eu/esdihumboldt/hale/io/json/test/JsonSchemaReaderTest.groovy, io/plugins/eu.esdihumboldt.hale.io.json/META-INF/MANIFEST.MF, io/plugins/eu.esdihumboldt.hale.io.json/plugin.xml, io/plugins/eu.esdihumboldt.hale.io.json/src/eu/esdihumboldt/hale/io/json/JsonSchemaReader.java, io/plugins/eu.esdihumboldt.hale.io.json/src/eu/esdihumboldt/hale/io/json/internal/JsonInstanceProcessor.java, io/plugins/eu.esdihumboldt.hale.io.json/src/eu/esdihumboldt/hale/io/json/internal/JsonToInstance.java, io/plugins/eu.esdihumboldt.hale.io.json/src/eu/esdihumboldt/hale/io/json/internal/schema/JsonProperty.groovy, io/plugins/eu.esdihumboldt.hale.io.json/src/eu/esdihumboldt/hale/io/json/internal/schema/JsonToSchema.java, io/plugins/eu.esdihumboldt.hale.io.json/src/eu/esdihumboldt/hale/io/json/internal/schema/JsonType.java, io/plugins/eu.esdihumboldt.hale.io.json/src/eu/esdihumboldt/hale/io/json/internal/schema/JsonTypes.java, io/plugins/eu.esdihumboldt.hale.io.json/src/eu/esdihumboldt/hale/io/json/internal/schema/JsonValueType.java, io/plugins/eu.esdihumboldt.hale.io.json/src/eu/esdihumboldt/hale/io/json/internal/schema/SchemaBuilderContext.java, ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/io/source/FileSource.java
First version that comes with some known restrictions:
- Parameters for the reader are not configurable in the UI, so e.g. the read mode can't be selected and only Json arrays and GeoJson FeatureCollections are supported in the UI at the moment.
- The schema reader only considers the first 50 objects encountered in the Json data. This is currently not configurable.
- Nested arrays (array of arrays) are not supported
ING-4046
=> feat: support loading schema from Json data

ext/styledmap/de.fhg.igd.mapviewer.server.tiles/src/de/fhg/igd/mapviewer/server/tiles/CustomTileMapServerFactory.java, ext/styledmap/org.jdesktop.swingx.mapviewer/META-INF/MANIFEST.MF, ext/styledmap/org.jdesktop.swingx.mapviewer/src/org/jdesktop/swingx/mapviewer/AbstractTileCache.java, ext/styledmap/org.jdesktop.swingx.mapviewer/src/org/jdesktop/swingx/mapviewer/DefaultTileFactory.java, io/plugins/eu.esdihumboldt.hale.io.wfs.ui/src/eu/esdihumboldt/hale/io/wfs/ui/getfeature/BBOXPage.java
Replaces the Stamen Terrain default map by OpenStreetMap.
To comply with the [usage policy of the OpenStreetMap tile server](https://operations.osmfoundation.org/policies/tiles/), the number of parallel connections is reduced to two and a HTTP User-Agent header is added to the requests.
The old default map configuration, if present, is automatically removed and the new default configuration is added.
ING-4081
=> Replace default map by OpenStreetMap

common/plugins/eu.esdihumboldt.hale.common.schema/src/eu/esdihumboldt/hale/common/schema/model/impl/DefaultTypeIndex.java
This serves to maintain type order in cases where this might matter and to minimize changes to exported Hale Schema Definition files.
ING-4062
=> refactor: maintain order of types in DefaultTypeIndex

io/plugins/eu.esdihumboldt.hale.io.csv.ui/src/eu/esdihumboldt/hale/io/csv/ui/DefaultSchemaTypePage.java, io/plugins/eu.esdihumboldt.hale.io.xls.ui/plugin.xml, io/plugins/eu.esdihumboldt.hale.io.xls.ui/src/eu/esdihumboldt/hale/io/xls/ui/XLSInstanceImportConfigurationPage.java, io/plugins/eu.esdihumboldt.hale.io.xls.ui/src/eu/esdihumboldt/hale/io/xls/ui/XLSSchemaTypePage.java, io/plugins/eu.esdihumboldt.hale.io.xls/META-INF/MANIFEST.MF, io/plugins/eu.esdihumboldt.hale.io.xls/src/eu/esdihumboldt/hale/io/xls/AbstractAnalyseTable.java, io/plugins/eu.esdihumboldt.hale.io.xls/src/eu/esdihumboldt/hale/io/xls/AnalyseXLSSchemaTable.java, io/plugins/eu.esdihumboldt.hale.io.xls/src/eu/esdihumboldt/hale/io/xls/XLSUtil.java, io/plugins/eu.esdihumboldt.hale.io.xls/src/eu/esdihumboldt/hale/io/xls/reader/DefaultXLSLookupTableReader.java
It is possible to load XLSX with multiple sheets that may contain blank sheets or rows or cells, both as source data and schema. Wizard: add the last 2 steps in one single step.
ING-4075
=> fix: Enable loading XSLX with blank rows and sheets for schema and source data

io/plugins/eu.esdihumboldt.hale.io.csv/src/eu/esdihumboldt/hale/io/csv/InstanceTableIOConstants.java, io/plugins/eu.esdihumboldt.hale.io.csv/src/eu/esdihumboldt/hale/io/csv/writer/AbstractTableInstanceWriter.java, io/plugins/eu.esdihumboldt.hale.io.xls.test/src/eu/esdihumboldt/hale/io/xls/test/XLSInstanceIOTest.java, io/plugins/eu.esdihumboldt.hale.io.xls.test/src/eu/esdihumboldt/hale/io/xls/test/writer/XLSInstanceWriterTest.java, io/plugins/eu.esdihumboldt.hale.io.xls.ui/src/eu/esdihumboldt/hale/io/xls/ui/XLSInstanceExportConfigurationPage.java, io/plugins/eu.esdihumboldt.hale.io.xls/plugin.xml, io/plugins/eu.esdihumboldt.hale.io.xls/src/eu/esdihumboldt/hale/io/xls/writer/XLSInstanceWriter.java
Users can select feature types without data for both: 
> Custom export configuration for hale-connect using Excel as output type 
> Export of transformed data as Excel from hale-studio
For the feature types without data there is the indication in the label that _[no data]_  is present. Has been reintroduced the button "**Exclude feature types without data**"
ING-4107
=> hale: Enable exporting feature types with no data

io/plugins/eu.esdihumboldt.hale.io.topojson.test/META-INF/MANIFEST.MF, io/plugins/eu.esdihumboldt.hale.io.topojson.test/src/eu/esdihumboldt/hale/io/topojson/test/TopoJsonInstanceWriterTest.groovy, io/plugins/eu.esdihumboldt.hale.io.topojson/META-INF/MANIFEST.MF, io/plugins/eu.esdihumboldt.hale.io.topojson/src/eu/esdihumboldt/hale/io/topojson/TopoJsonInstanceWriter.java
Use Jackson's ObjectMapper to parse the JSON string into a JsonNode, then recursively traverses the JsonNode to replace "null" values with null. Finally, it converts the modified JsonNode back to a JSON string.
ING-3979
=> fix: Fix TopoJSON encoding issue

io/plugins/eu.esdihumboldt.hale.io.json/src/eu/esdihumboldt/hale/io/json/internal/InstanceToJson.java
For hale studio it does not make sense to limit
decimal places so that the original data remains
intact. However, we need to provide some value
to Geotools and it does not make sense to configure max integer. 
Therefore, providing higher value of 20 to Geotools even if it 
represents some kind of ridiculous  "accuracy" for WGS 84.
=> fix: Update decimal places to 20 for Geotools

util/plugins/eu.esdihumboldt.util.groovy.sandbox/src/eu/esdihumboldt/util/groovy/sandbox/internal/RestrictiveGroovyInterceptor.java
Add the class java.util.regex.Pattern to the allowedClasses list in the RestrictiveGroovyInterceptor.
ING-4168
=> feat: allowed java Pattern class to the used into regular expressions

io/plugins/eu.esdihumboldt.hale.io.csv.test/src/data/test3.csv, io/plugins/eu.esdihumboldt.hale.io.csv.test/src/eu/esdihumboldt/hale/io/csv/CSVInstanceReaderTest.java, io/plugins/eu.esdihumboldt.hale.io.csv.ui/src/eu/esdihumboldt/hale/io/csv/ui/TypeSelectionPage.java, io/plugins/eu.esdihumboldt.hale.io.csv/plugin.xml, io/plugins/eu.esdihumboldt.hale.io.csv/src/eu/esdihumboldt/hale/io/csv/reader/CSVConstants.java, io/plugins/eu.esdihumboldt.hale.io.csv/src/eu/esdihumboldt/hale/io/csv/reader/internal/CSVInstanceCollection.java, io/plugins/eu.esdihumboldt.hale.io.csv/src/eu/esdihumboldt/hale/io/csv/reader/internal/CSVInstanceReader.java, io/plugins/eu.esdihumboldt.hale.io.xls.test/src/eu/esdihumboldt/hale/io/xls/test/reader/XLSReaderTest.java, io/plugins/eu.esdihumboldt.hale.io.xls.ui/src/eu/esdihumboldt/hale/io/xls/ui/XLSInstanceImportConfigurationPage.java, io/plugins/eu.esdihumboldt.hale.io.xls/src/eu/esdihumboldt/hale/io/xls/AbstractAnalyseTable.java, io/plugins/eu.esdihumboldt.hale.io.xls/src/eu/esdihumboldt/hale/io/xls/reader/ReaderSettings.java, io/plugins/eu.esdihumboldt.hale.io.xls/src/eu/esdihumboldt/hale/io/xls/reader/XLSInstanceReader.java, io/plugins/eu.esdihumboldt.hale.io.xls/src/eu/esdihumboldt/hale/io/xls/reader/XLSSchemaReader.java
The issue has been extended to CSV as well, as the code is/might be common in some points. 
Add a combo box with different patterns for the date formatter + a custom text. This pattern is then used when importing cells/rows of type Date.
ING-4165
=> fix/feat:  add GUI parameter to select date formatter for the Excel/CSV

common/plugins/eu.esdihumboldt.hale.common.instance/src/eu/esdihumboldt/hale/common/instance/model/Identifiable.java
Due to the wrong check, the index based Merge and Join handlers were not used at all. Also, no instances were added to the index service.
=> fix: fix check if an object is identifiable

platform/hale-platform.target, ui/plugins/eu.esdihumboldt.hale.ui.application/HALE.product, util/features/eu.esdihumboldt.util.feature.resource/feature.xml
Replace the offline resource bundles created as part of hale-platform by bundles created using the offline-resource repository. The related build and bundles in hale-platform become obsolete.
=> build: use separate update site for offline resource bundles

common/plugins/eu.esdihumboldt.hale.common.align/src/eu/esdihumboldt/hale/common/align/transformation/function/PropertyValue.java, common/plugins/eu.esdihumboldt.hale.common.align/src/eu/esdihumboldt/hale/common/align/transformation/function/impl/PropertyValueImpl.java, common/plugins/eu.esdihumboldt.hale.common.instance.orient/src/eu/esdihumboldt/hale/common/instance/orient/internal/OSerializationHelper.java, cst/plugins/eu.esdihumboldt.cst.test/src/eu/esdihumboldt/cst/internal/ConceptualSchemaTransformerTest.java, cst/plugins/eu.esdihumboldt.cst.test/src/eu/esdihumboldt/cst/test/TransformationExamples.groovy, cst/plugins/eu.esdihumboldt.cst.test/testdata/formatting_string_instance/mapping.halex, cst/plugins/eu.esdihumboldt.cst.test/testdata/formatting_string_instance/mapping.halex.alignment.xml, cst/plugins/eu.esdihumboldt.cst.test/testdata/formatting_string_instance/mapping.halex.styles.sld, cst/plugins/eu.esdihumboldt.cst.test/testdata/formatting_string_instance/source-instances.groovy, cst/plugins/eu.esdihumboldt.cst.test/testdata/formatting_string_instance/source-schema.groovy, cst/plugins/eu.esdihumboldt.cst.test/testdata/formatting_string_instance/target-instances.groovy, cst/plugins/eu.esdihumboldt.cst.test/testdata/formatting_string_instance/target-schema.groovy
For a formatting string or a regex the string that appears into the occurring values as "eu.esdihumboldt.hale.common.instance.orient.storage.DatabaseHandle$InstanceHandle@1008ac5f" it's now represented with the value of the source.
ING-4156
=> fix:  functions not working for elements with value and attribute

common/plugins/eu.esdihumboldt.hale.common.align/src/eu/esdihumboldt/hale/common/align/model/impl/DefaultAlignment.java
...when selecting a source type in the alignment view.
Before no results would be shown because the internal check expects all types to match while in the view only one can be specified.
=> fix: allow filtering for joins

platform/hale-platform.target
Includes changes to INSPIRE schemas done after the hale 5.1 release,
that were not added yet, because the download mechanism was not working
as expected.
=> chore(deps): update offline resources

.github/workflows/check.yml, .github/workflows/publish.yml, .github/workflows/release.yml, build/gradle/commitAndProductionStage.gradle, build/gradle/updateSite.gradle
Add pull request file, master and release branches files to be used by the GitHub actions to check the PRs.
ING-4164
=> build: migrate build to GitHub Actions

common/plugins/eu.esdihumboldt.hale.common.core/plugin.xml, common/plugins/eu.esdihumboldt.hale.common.core/src/eu/esdihumboldt/hale/common/core/service/DelegateServiceProvider.java, common/plugins/eu.esdihumboldt.hale.common.lookup/plugin.xml, cst/plugins/eu.esdihumboldt.cst.functions.groovy/src/eu/esdihumboldt/cst/functions/groovy/GroovyConstants.java, cst/plugins/eu.esdihumboldt.cst.functions.groovy/src/eu/esdihumboldt/cst/functions/groovy/internal/GroovyUtil.java
=> feat: bind lookup service to Groovy constant for use in scripts

.github/workflows/publish.yml
It looks like the Artifactory secrets are not passed to the `deployArtifacts` task, so adding them to `env` explicitly here. If this solves the problem that the `uploadEclipse` step is currently not executed remains to be seen.
=> ci: pass Artifactory user and password to deployArtifacts task

io/plugins/eu.esdihumboldt.hale.io.gml/plugin.xml, io/plugins/eu.esdihumboldt.hale.io.wfs/plugin.xml
Up to now the `providerParameter` definitions for the parameter `geometry.unifyWindingOrder` contained values that were inconsistent with the corresponding enumeration `EnumWindingOrderTypes`.
Using the inconsistent values in CLI transformations could lead to unexpected results when using the value of the parameters given in the documentation that is derived from the `providerParameter` definitions.
=> fix: fix provider definition for geometry.unifyWindingOrder parameters

io/plugins/eu.esdihumboldt.hale.io.wfs.ui/src/eu/esdihumboldt/hale/io/wfs/ui/getfeature/GetFeatureParamsPage.java, io/plugins/eu.esdihumboldt.hale.io.wfs.ui/src/eu/esdihumboldt/hale/io/wfs/ui/getfeature/WFSGetFeatureConfig.groovy, io/plugins/eu.esdihumboldt.hale.io.wfs.ui/src/eu/esdihumboldt/hale/io/wfs/ui/getfeature/WFSGetFeatureSource.java
Add in the dialog for the WFS GetCapability the possibility to choose if you want to add a resolveDepth for a request and how much would that be. Has been added a spinner to choose a number above 0 or the '*' for all the possible depths to be resolved.
ING-4129
Closes [#1085](https://github.com/halestudio/hale/issues/1085)
=> feat: add paramter "resolvedepth" in UI when downloading data via WFS

doc/plugins/eu.esdihumboldt.hale.doc.user/html/new/latest.xhtml, doc/plugins/eu.esdihumboldt.hale.doc.user/toc.xml
=> docs: add generic what's new page referencing release page

ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/service/project/internal/ProjectServiceImpl.java
By using the "Reload and update schemas" button the saving function it's working saving all the changes done to the project.
ING-4307
Closes #956
=> fix: Reload and update schemas - saves the last changes

io/plugins/eu.esdihumboldt.hale.io.gml.test/src/data/numbers/numbers.xsd, io/plugins/eu.esdihumboldt.hale.io.gml.test/src/data/shiporder/shiporder.xml, io/plugins/eu.esdihumboldt.hale.io.gml.test/src/data/shiporder/shiporder.xsd, io/plugins/eu.esdihumboldt.hale.io.gml.test/src/eu/esdihumboldt/hale/io/gml/reader/internal/GmlInstanceCollectionTest.java, io/plugins/eu.esdihumboldt.hale.io.gml.test/src/eu/esdihumboldt/hale/io/gml/writer/internal/StreamGmlWriter2Test.groovy, io/plugins/eu.esdihumboldt.hale.io.gml/plugin.xml, io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/internal/simpletype/SimpleTypeUtil.java, io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/internal/simpletype/converters/BigDecimalToXmlDecimal.java, io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/internal/simpletype/converters/BigIntegerToXmlInteger.java, io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/internal/simpletype/converters/DoubleToXmlDouble.java, io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/internal/simpletype/converters/FloatToXmlFloat.java, io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/internal/simpletype/converters/IntegerToXmlInt.java, io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/internal/simpletype/converters/IntegerToXmlInteger.java, io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/internal/simpletype/converters/LongToXmlLong.java, io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/internal/simpletype/converters/ShortToXmlShort.java, io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/internal/simpletype/converters/XmlDecimalToBigDecimal.java, io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/internal/simpletype/converters/XmlDoubleToDouble.java, io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/internal/simpletype/converters/XmlFloatToFloat.java, io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/internal/simpletype/converters/XmlIntToInteger.java, io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/internal/simpletype/converters/XmlIntegerToBigInteger.java, io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/internal/simpletype/converters/XmlIntegerToInteger.java, io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/internal/simpletype/converters/XmlLongToLong.java, io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/internal/simpletype/converters/XmlShortToShort.java
Conversion of the numbers using appropriate methods of each different type.
ING-3965
=> fix: use appropriate methods to convert the numbers in XML

common/plugins/eu.esdihumboldt.hale.common.instance.orient/src/eu/esdihumboldt/hale/common/instance/orient/storage/BrowseOrientInstanceCollection.java, cst/plugins/eu.esdihumboldt.cst.functions.geometric/src/eu/esdihumboldt/cst/functions/geometric/CalculateArea.java, cst/plugins/eu.esdihumboldt.cst.functions.geometric/src/eu/esdihumboldt/cst/functions/geometric/CalculateLength.java
Solve the vulnerability raised by CodeQL scanning for the implicit narrowing conversion in compound assignment.
ING-4370
=> fix: implicit narrowing conversion in compound assignment

io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/internal/simpletype/SimpleTypeUtil.java
Resolves issue introduced in 5.2.0 release.
Conversion to XmlDate and XmlDateTime was done but the result not used.
=> fix: use correct representation of date and time when exporting XML/GML

ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/service/groovy/internal/PreferencesGroovyService.java
Replace MD5 with SH-256 because MD5 is susceptible to several vulnerabilities, including collision attacks. By switching from MD5 to SHA-256, we enhance the security of your hashing process, making it suitable for modern cryptographic applications.
ING-4368
=> fix: usage of a broken or risky cryptographic algorithm

common/plugins/eu.esdihumboldt.hale.common.instance.graph/src/eu/esdihumboldt/hale/common/instance/graph/reference/ReferenceGraph.java, io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/writer/XPlanGmlInstanceWriter.java
=> fix: Xplan validation erroneously throws warning on missing objects

common/plugins/eu.esdihumboldt.hale.common.core/src/eu/esdihumboldt/hale/common/core/io/project/impl/ArchiveProjectImport.java, platform/tools/Servicemerger/src/Servicemerger.java, util/plugins/eu.esdihumboldt.util/src/eu/esdihumboldt/util/reflection/ReflectionHelper.java
Ensure that output paths constructed from zip archive entries are validated to prevent writing files to unexpected locations.
ING-4369
=> fix: arbitrary file access during archive extraction ("Zip Slip")

.github/workflows/publish.yml, .github/workflows/release.yml
...to avoid conflicts with new hale-core repository.
Also remove execution of Docker integration tests that don't work due to the outdated Docker client.
ING-4375
ING-4362
Related to https://github.com/halestudio/hale-core/pull/11
=> ci: disable publishing Maven artifacts

cst/plugins/eu.esdihumboldt.cst.functions.core/src/eu/esdihumboldt/cst/functions/core/Join.java
...to match similar name of similar properties and environment variables.
New name also matches the documentation.
Backported from https://github.com/halestudio/hale-core/pull/117
=> fix: adapt name of system property for join handler

.github/workflows/publish.yml
This is necessary because the name of the product was changed in 17d36207583dad9c48b305ebab48f3aad6159db1
=> ci: exclude infocenter from published linux artifact

.github/workflows/publish.yml
On the command line, a tar archive is easier to handle than the `.dmg` file.
=> ci: include tar archive in published macOS build artifact

.github/workflows/check.yml
On the command line, a tar archive is easier to handle than the `.dmg` file.
Same change for the `check` workflow that was done in #1320 for the `publish` workflow
=> ci: include tar archive in macOS PR build artifact
