common/plugins/eu.esdihumboldt.hale.common.convert.core/src/eu/esdihumboldt/hale/common/convert/core/SqlTimestampToSqlDateConverter.java, common/plugins/eu.esdihumboldt.hale.common.instance/src/eu/esdihumboldt/hale/common/instance/model/InstanceUtil.java, io/plugins/eu.esdihumboldt.hale.io.jdbc.postgresql.test/src/eu/esdihumboldt/hale/io/jdbc/postgresql/test/PostDataTypesTest.groovy, io/plugins/eu.esdihumboldt.hale.io.jdbc.postgresql/plugin.xml, io/plugins/eu.esdihumboldt.hale.io.jdbc.test/META-INF/MANIFEST.MF, io/plugins/eu.esdihumboldt.hale.io.jdbc.test/src/eu/esdihumboldt/hale/io/jdbc/test/AbstractDBTest.java, io/plugins/eu.esdihumboldt.hale.io.jdbc/META-INF/MANIFEST.MF, platform/hale-platform.target
Hello Simon,
Created the unit test case for testing sql type and expected binding of data types for postgresql.
Regards,
Sameer Sheikh
=> Test for checking sql type and binding

io/plugins/eu.esdihumboldt.hale.io.appschema.test/src/eu/esdihumboldt/hale/io/geoserver/rest/ResourceManagerIT.java
Fixed according to discussion on [previous PR](https://github.com/igd-geo/hale/pull/9).
=> Fix integration tests naming and server availability check

io/plugins/eu.esdihumboldt.hale.io.appschema.ui/src/eu/esdihumboldt/hale/io/appschema/ui/AppSchemaDataStoreConfigurationPage.java
* Improved validation of DataStore configuration
* *Expose primary key* flag defaults to `true`
=> App-Schema plug-in: DataStore conf page improvements

common/plugins/eu.esdihumboldt.hale.common.core/src/eu/esdihumboldt/hale/common/core/io/project/ProjectVariables.java
Change-Id: I98356d55273d7a048a03ab9ede41deab5b958708
=> fixed false error messages when no project variables are defined

ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/service/instance/internal/AbstractInstanceService.java
Change-Id: Iac0e973dcb919d6ec0105ca7c4c974b38b27bd6a
=> retransform on project variable change

common/plugins/eu.esdihumboldt.hale.common.schema/plugin.xml, cst/plugins/eu.esdihumboldt.cst.functions.custom.test/src/eu/esdihumboldt/cst/functions/custom/test/internal/DefaultCustomPropertyFunctionTypeTest.java, cst/plugins/eu.esdihumboldt.cst.functions.custom/src/eu/esdihumboldt/hale/common/align/custom/DefaultCustomPropertyFunction.java, cst/plugins/eu.esdihumboldt.cst.functions.custom/src/eu/esdihumboldt/hale/common/align/custom/DefaultCustomPropertyFunctionParameter.java, cst/plugins/eu.esdihumboldt.cst.functions.custom/src/eu/esdihumboldt/hale/common/align/custom/DefaultCustomPropertyFunctionParameterDefinition.java, cst/plugins/eu.esdihumboldt.cst.functions.custom/src/eu/esdihumboldt/hale/common/align/custom/MinimalParameter.java, cst/plugins/eu.esdihumboldt.cst.functions.custom/src/eu/esdihumboldt/hale/common/align/custom/groovy/CustomGroovyTransformation.java, cst/plugins/eu.esdihumboldt.cst.functions.custom/src/eu/esdihumboldt/hale/common/align/custom/internal/DefaultCustomPropertyFunctionType.groovy, ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/service/groovy/internal/PreferencesGroovyService.java
No UI support in function editor.
=> Support simple parameters for custom functions

app/plugins/eu.esdihumboldt.hale.app.transform/META-INF/MANIFEST.MF
...that resulted in the CLI being unable to launch.
=> add missing runtime dependency

cst/plugins/eu.esdihumboldt.cst/.classpath, cst/plugins/eu.esdihumboldt.cst/.settings/org.eclipse.jdt.core.prefs, ui/plugins/eu.esdihumboldt.hale.ui.application/plugin.xml, util/plugins/eu.esdihumboldt.util.test/META-INF/MANIFEST.MF, util/plugins/eu.esdihumboldt.util.test/src/eu/esdihumboldt/util/geometry/WindingOrderTest.java, util/plugins/eu.esdihumboldt.util/META-INF/MANIFEST.MF, util/plugins/eu.esdihumboldt.util/src/eu/esdihumboldt/util/geometry/WindingOrder.java
Winding Order handling for Polygon, MultiPolygon, GeometryCollection, LinearString
=> Winding order handling for geometry objects

common/plugins/eu.esdihumboldt.hale.common.instance.orient/.classpath, common/plugins/eu.esdihumboldt.hale.common.instance.orient/.settings/org.eclipse.jdt.core.prefs, common/plugins/eu.esdihumboldt.hale.common.instance.orient/META-INF/MANIFEST.MF, common/plugins/eu.esdihumboldt.hale.common.instance.orient/src/eu/esdihumboldt/hale/common/instance/orient/storage/BrowseOrientInstanceCollection.java, common/plugins/eu.esdihumboldt.hale.common.instance.orient/src/eu/esdihumboldt/hale/common/instance/orient/storage/DatabaseHandle.java, common/plugins/eu.esdihumboldt.hale.common.instance.orient/src/eu/esdihumboldt/hale/common/instance/orient/storage/OrientInstanceReference.java, common/plugins/eu.esdihumboldt.hale.common.instance.orient/src/eu/esdihumboldt/hale/common/instance/orient/storage/SQLQueryInstanceCollection.java, common/plugins/eu.esdihumboldt.hale.common.instance/src/eu/esdihumboldt/hale/common/instance/model/impl/GroupDecorator.java
=> DatabaseHandle: add references for child instances and groups

cst/plugins/eu.esdihumboldt.cst.functions.custom/src/eu/esdihumboldt/hale/common/align/custom/DefaultCustomPropertyFunctionEntity.java
Fixes custom function definition being changed unintentionally on save.
=> no default binding for custom function entities

common/plugins/eu.esdihumboldt.hale.common.convert.core/META-INF/MANIFEST.MF, common/plugins/eu.esdihumboldt.hale.common.convert.core/plugin.xml, common/plugins/eu.esdihumboldt.hale.common.convert.core/src/eu/esdihumboldt/hale/common/convert/core/GStringImplToURIConverter.java
...commonly needed with Groovy script transformations.
=> added GString to URI converter

io/plugins/eu.esdihumboldt.hale.io.jdbc.msaccess.test/META-INF/MANIFEST.MF, io/plugins/eu.esdihumboldt.hale.io.jdbc.msaccess.test/src/eu/esdihumboldt/hale/io/jdbc/msaccess/reader/MsAccessInstanceReaderTest.java, io/plugins/eu.esdihumboldt.hale.io.jdbc.msaccess.test/src/eu/esdihumboldt/hale/io/jdbc/msaccess/test/MsAccessDataReaderTestSuit.java, io/plugins/eu.esdihumboldt.hale.io.jdbc.msaccess/plugin.xml, io/plugins/eu.esdihumboldt.hale.io.jdbc.msaccess/src/eu/esdihumboldt/hale/io/jdbc/msaccess/MsAccessInstanceReader.java, io/plugins/eu.esdihumboldt.hale.io.jdbc/src/eu/esdihumboldt/hale/io/jdbc/JDBCInstanceReader.java, io/plugins/eu.esdihumboldt.hale.io.jdbc/src/eu/esdihumboldt/hale/io/jdbc/constraints/DatabaseTable.java
Created MsAccess Instance Reader..
=> MsAccess Instance Reader

ui/plugins/eu.esdihumboldt.hale.ui.common.graph/src/eu/esdihumboldt/hale/ui/common/graph/labels/GraphLabelProvider.java
...when a used function does not have an image.
=> fix possible NPE w/ base alignment cells

platform/hale-platform.target
=> updated target platform

common/plugins/eu.esdihumboldt.hale.common.align.test/META-INF/MANIFEST.MF, common/plugins/eu.esdihumboldt.hale.common.align.test/src/eu/esdihumboldt/hale/common/align/io/JaxbAlignmentIOTest.java, common/plugins/eu.esdihumboldt.hale.common.align/src/eu/esdihumboldt/hale/common/align/io/impl/JaxbAlignmentIO.java, common/plugins/eu.esdihumboldt.hale.common.align/src/eu/esdihumboldt/hale/common/align/io/impl/JaxbAlignmentWriter.java, common/plugins/eu.esdihumboldt.hale.common.align/src/eu/esdihumboldt/hale/common/align/io/impl/internal/AlignmentToJaxb.groovy, common/plugins/eu.esdihumboldt.hale.common.align/src/eu/esdihumboldt/hale/common/align/io/impl/internal/CellOrModifierComparator.groovy, common/plugins/eu.esdihumboldt.hale.common.core/src/eu/esdihumboldt/hale/common/core/io/project/extension/internal/ActionProjectFile.java
closes #63 
Also improved handling of errors occurring while saving the alignment that would result in the alignment being overridden by an empty file.
=> Sort cells when writing an alignment to file

common/plugins/eu.esdihumboldt.hale.common.align/src/eu/esdihumboldt/hale/common/align/io/impl/internal/AbstractBaseAlignmentLoader.java
Interestingly enough, this doesn't happen when loading such
an alignment in the UI.
=> fix alignment loading failing with duplicate base alignments

cst/plugins/eu.esdihumboldt.cst/src/eu/esdihumboldt/cst/internal/TreePropertyTransformer.java
Short term fix for #96 
First tests regarding transformation speed showed about 25% longer duration for the instance transformation part (in the example that meant about 12% increase in the overall duration).
=> transformation in one thread

io/plugins/eu.esdihumboldt.hale.io.wfs/plugin.xml, io/plugins/eu.esdihumboldt.hale.io.wfs/src/eu/esdihumboldt/hale/io/wfs/file/WFSFeatureCollectionWriter.java
Allows using WFS 2 FeatureCollection writer as passthrough writer.
=> add parameter for WFS FC writer to skip count

ext/styledmap/de.fhg.igd.mapviewer.server.openstreetmap/src/de/fhg/igd/mapviewer/server/openstreetmap/OpenStreetMapServer.java, ext/styledmap/de.fhg.igd.mapviewer.server.tiles/META-INF/MANIFEST.MF, ext/styledmap/eu.esdihumboldt.hale.ui.views.styledmap.feature/feature.xml, io/plugins/eu.esdihumboldt.hale.io.wfs.ui/META-INF/MANIFEST.MF, io/plugins/eu.esdihumboldt.hale.io.wfs.ui/src/eu/esdihumboldt/hale/io/wfs/ui/getfeature/BBOXPage.java
=> remove MapQuest OSM map from product

common/plugins/eu.esdihumboldt.hale.common.instance/src/eu/esdihumboldt/hale/common/instance/geometry/impl/CodeDefinition.java, cst/plugins/eu.esdihumboldt.cst.functions.geometric/src/eu/esdihumboldt/cst/functions/geometric/CRSHelperFunctions.groovy, io/plugins/eu.esdihumboldt.hale.io.jdbc.postgresql/src/eu/esdihumboldt/hale/io/jdbc/postgresql/PostGISGeometries.java
=> fix axis order for PostGIS

ui/plugins/eu.esdihumboldt.hale.ui.views.schemas/src/eu/esdihumboldt/hale/ui/views/schemas/SchemasView.java
=> size hint for schema explorers in schemas view

io/plugins/eu.esdihumboldt.hale.io.gml.test/.classpath, io/plugins/eu.esdihumboldt.hale.io.gml.test/.project, io/plugins/eu.esdihumboldt.hale.io.gml.test/META-INF/MANIFEST.MF, io/plugins/eu.esdihumboldt.hale.io.gml.test/src/eu/esdihumboldt/hale/io/gml/writer/internal/StreamGmlWriterTest.java, io/plugins/eu.esdihumboldt.hale.io.gml.test/src/eu/esdihumboldt/hale/io/gml/writer/internal/StreamGmlWriterTest2.groovy, io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/writer/internal/geometry/StreamGeometryWriter.java, io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/writer/internal/geometry/writers/CurveSingleSegmentWriter.java
Also added corresponding tests.
=> fix writing curves being represented by a single LineString

cst/plugins/eu.esdihumboldt.cst.functions.groovy/META-INF/MANIFEST.MF, cst/plugins/eu.esdihumboldt.cst.functions.groovy/src/eu/esdihumboldt/cst/functions/groovy/filter/GroovyFilter.java, cst/plugins/eu.esdihumboldt.cst.functions.groovy/src/eu/esdihumboldt/cst/functions/groovy/filter/LogWrapper.java
...with at least 3 changes in minor versions in 1.7.x
=> SubstituteLogger seems to have a very unstable constructor

io/plugins/eu.esdihumboldt.hale.io.csv.ui/src/eu/esdihumboldt/hale/io/csv/ui/AbstractCSVConfigurationPage.java, io/plugins/eu.esdihumboldt.hale.io.csv/src/eu/esdihumboldt/hale/io/csv/reader/CSVConstants.java, io/plugins/eu.esdihumboldt.hale.io.csv/src/eu/esdihumboldt/hale/io/csv/reader/internal/CSVInstanceReader.java, io/plugins/eu.esdihumboldt.hale.io.csv/src/eu/esdihumboldt/hale/io/csv/reader/internal/CSVUtil.java
ConversionService has been used to convert one type to another. So need to be sure first with Simon.
issue #130
=> Handling decimal with comma for CSV Reader

ui/plugins/eu.esdihumboldt.hale.ui.views.data/src/eu/esdihumboldt/hale/ui/views/data/AbstractDataView.java, ui/plugins/eu.esdihumboldt.hale.ui.views.data/src/eu/esdihumboldt/hale/ui/views/data/TransformedDataView.java
=> Solved creation of extra controls in Transformed Data View

ui/plugins/eu.esdihumboldt.hale.ui.views.data/src/eu/esdihumboldt/hale/ui/views/data/AbstractDataView.java, ui/plugins/eu.esdihumboldt.hale.ui.views.data/src/eu/esdihumboldt/hale/ui/views/data/internal/filter/InstanceSelectionListener.java, ui/plugins/eu.esdihumboldt.hale.ui.views.data/src/eu/esdihumboldt/hale/ui/views/data/internal/filter/SampleTransformInstanceSelector.java
=> Changes related to issue in Transformed Data view

app/plugins/eu.esdihumboldt.hale.app.transform.test/src/eu/esdihumboldt/hale/app/transform/test/ExecuteTest.groovy, common/plugins/eu.esdihumboldt.hale.common.headless/src/eu/esdihumboldt/hale/common/headless/transform/filter/InstanceFilterDefinition.java, doc/plugins/eu.esdihumboldt.hale.doc.user/html/tasks/transform_cli.html
=> change type filter only behavior, add documentation for CLI filters

ui/plugins/eu.esdihumboldt.hale.ui.views.data/src/eu/esdihumboldt/hale/ui/views/data/AbstractDataView.java, ui/plugins/eu.esdihumboldt.hale.ui.views.data/src/eu/esdihumboldt/hale/ui/views/data/TransformedDataView.java
=> Showing progress bar in transformed data view

app/plugins/eu.esdihumboldt.hale.app.transform/src/eu/esdihumboldt/hale/app/transform/ExecApplication.groovy, cst/plugins/eu.esdihumboldt.cst.functions.groovy/help/common.xhtml, cst/plugins/eu.esdihumboldt.cst.functions.groovy/help/create.xhtml, cst/plugins/eu.esdihumboldt.cst.functions.groovy/help/join.xhtml, cst/plugins/eu.esdihumboldt.cst.functions.groovy/help/merge.xhtml, cst/plugins/eu.esdihumboldt.cst.functions.groovy/help/retype.xhtml, cst/plugins/eu.esdihumboldt.cst.functions.groovy/help/script.xhtml, doc/plugins/eu.esdihumboldt.hale.doc.user/html/concepts/cell_priority.html
=> updated help for Groovy scripts and cell priority

io/plugins/eu.esdihumboldt.hale.io.html.svg/src/eu/esdihumboldt/hale/io/html/svg/mapping/MappingExporter.java
=> use release version of halejs

io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/writer/internal/StreamGmlWriter.java, io/plugins/eu.esdihumboldt.hale.io.xsd/src/eu/esdihumboldt/hale/io/xsd/reader/XmlSchemaReader.java
=> Use "other:unpopulated" for INSPIRE nilReason "unpopulated"

ui/plugins/eu.esdihumboldt.hale.ui.common/src/eu/esdihumboldt/hale/ui/common/definition/viewer/OptionalPropertiesFilter.java
=> optional properties filter including fixes

ui/plugins/eu.esdihumboldt.hale.ui.common/src/eu/esdihumboldt/hale/ui/common/definition/viewer/OptionalPropertiesFilter.java
group is added in the filter check. Related to #175
=> Optional Properties filter

io/plugins/eu.esdihumboldt.hale.io.gml.geometry/src/eu/esdihumboldt/hale/io/gml/geometry/handler/ArcHandler.java, util/plugins/eu.esdihumboldt.util.test/src/eu/esdihumboldt/util/geometry/interpolation/InterpolationGridCellTest.java, util/plugins/eu.esdihumboldt.util.test/src/eu/esdihumboldt/util/geometry/interpolation/InterpolationTest.java, util/plugins/eu.esdihumboldt.util/src/eu/esdihumboldt/util/geometry/interpolation/ArcInterpolation.java, util/plugins/eu.esdihumboldt.util/src/eu/esdihumboldt/util/geometry/interpolation/Interpolation.java
=> bug fixing of interpolation of arc

common/plugins/eu.esdihumboldt.hale.common.instance/src/eu/esdihumboldt/hale/common/instance/geometry/curve/InterpolationConstant.java, io/plugins/eu.esdihumboldt.hale.io.gml.geometry/src/eu/esdihumboldt/hale/io/gml/geometry/handler/ArcHandler.java, io/plugins/eu.esdihumboldt.hale.io.interpolation.ui/src/eu/esdihumboldt/hale/io/interpolation/ui/InterpolationSettingPage.java, util/plugins/eu.esdihumboldt.util.test/src/eu/esdihumboldt/util/geometry/interpolation/InterpolationGridCellTest.java, util/plugins/eu.esdihumboldt.util.test/src/eu/esdihumboldt/util/geometry/interpolation/InterpolationTest.java, util/plugins/eu.esdihumboldt.util/src/eu/esdihumboldt/util/geometry/interpolation/ArcInterpolation.java, util/plugins/eu.esdihumboldt.util/src/eu/esdihumboldt/util/geometry/interpolation/Interpolation.java
Related to #219 
Changes done for mode 1. Working on mode 2.
=> Handling consisting points between different kind of geometries in interpolation

common/plugins/eu.esdihumboldt.hale.common.core/src/eu/esdihumboldt/hale/common/core/io/project/impl/ArchiveProjectWriter.java, common/plugins/eu.esdihumboldt.hale.common.core/src/eu/esdihumboldt/hale/common/core/io/project/impl/DefaultProjectReader.java, common/plugins/eu.esdihumboldt.hale.common.core/src/eu/esdihumboldt/hale/common/core/io/project/model/Project.java, ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/io/IOWizard.java
=> Fixed "Export -> Project archive" wizard

io/plugins/eu.esdihumboldt.hale.io.gml.geometry.test/src/eu/esdihumboldt/hale/io/gml/geometry/handler/compositeGeometries/CurveGeometryTest.java, io/plugins/eu.esdihumboldt.hale.io.gml.geometry.test/src/eu/esdihumboldt/hale/io/gml/geometry/handler/compositeGeometries/MultiSurfaceGeometryTest.java, io/plugins/eu.esdihumboldt.hale.io.gml.geometry/src/eu/esdihumboldt/hale/io/gml/geometry/handler/CircleHandler.java, io/plugins/eu.esdihumboldt.hale.io.gml.geometry/src/eu/esdihumboldt/hale/io/gml/geometry/handler/LineStringHandler.java, io/plugins/eu.esdihumboldt.hale.io.gml.geometry/src/eu/esdihumboldt/hale/io/gml/geometry/handler/PolygonHandler.java, util/plugins/eu.esdihumboldt.util.test/src/eu/esdihumboldt/util/geometry/interpolation/CircleInterpolationTest.java, util/plugins/eu.esdihumboldt.util.test/src/eu/esdihumboldt/util/geometry/interpolation/InterpolationGridCellTest.java, util/plugins/eu.esdihumboldt.util.test/src/eu/esdihumboldt/util/geometry/interpolation/arc/ArcInterpolationTest.java, util/plugins/eu.esdihumboldt.util.test/src/eu/esdihumboldt/util/geometry/interpolation/arc/ArcOrderTest.java, util/plugins/eu.esdihumboldt.util.test/src/eu/esdihumboldt/util/geometry/interpolation/util/DrawGeometry.java, util/plugins/eu.esdihumboldt.util/src/eu/esdihumboldt/util/geometry/interpolation/ArcInterpolation.java, util/plugins/eu.esdihumboldt.util/src/eu/esdihumboldt/util/geometry/interpolation/CircleInterpolation.java, util/plugins/eu.esdihumboldt.util/src/eu/esdihumboldt/util/geometry/interpolation/Interpolation.java
=> Arc interpolation fixing and added support for circle type

ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/service/population/internal/PopulationServiceImpl.java
=> removed counting for target context

ui/plugins/eu.esdihumboldt.hale.ui.views.mapping/src/eu/esdihumboldt/hale/ui/views/mapping/MappingView.java
=> handle updation of mapping view after edit/delete operation on cell

cst/plugins/eu.esdihumboldt.cst.functions.numeric/plugin.xml, cst/plugins/eu.esdihumboldt.cst.functions.numeric/src/eu/esdihumboldt/cst/functions/numeric/sequentialid/SequentialIDExplanation.java, cst/plugins/eu.esdihumboldt.cst.functions.numeric/src/eu/esdihumboldt/cst/functions/numeric/sequentialid/SequentialIDExplanation.md
=> added explanation page for sequential id function

io/plugins/eu.esdihumboldt.hale.io.codelist.skos.test/src/data/test4_lang.rdf, io/plugins/eu.esdihumboldt.hale.io.codelist.skos.test/src/data/test4_lang_fallback.rdf, io/plugins/eu.esdihumboldt.hale.io.codelist.skos.test/src/eu/esdihumboldt/hale/io/codelist/skos/test/SkosCodeListTest.java, io/plugins/eu.esdihumboldt.hale.io.codelist.skos/src/eu/esdihumboldt/hale/io/codelist/skos/reader/SkosCodeList.java, io/plugins/eu.esdihumboldt.hale.io.codelist.skos/src/eu/esdihumboldt/hale/io/codelist/skos/reader/SkosCodeListReader.java
=> added support to load system specific language SKOS code lists, if available

common/plugins/eu.esdihumboldt.hale.common.instance/src/eu/esdihumboldt/hale/common/instance/geometry/curve/InterpolationConstant.java, io/plugins/eu.esdihumboldt.hale.io.gml.geometry.test/src/eu/esdihumboldt/hale/io/gml/geometry/handler/internal/AbstractHandlerTest.java, io/plugins/eu.esdihumboldt.hale.io.gml.geometry/src/eu/esdihumboldt/hale/io/gml/geometry/InterpolationSupportedGeometryHandler.java, io/plugins/eu.esdihumboldt.hale.io.interpolation.ui/src/eu/esdihumboldt/hale/io/interpolation/ui/InterpolationSettingPage.java
...to interpolation grid.
It feels more natural to enable moving geometries to the grid instead of disabling keeping all geometries in their original state.
=> reverse behavior of parameter that controls moving geometries

cst/plugins/eu.esdihumboldt.cst.functions.custom/src/eu/esdihumboldt/hale/common/align/custom/DefaultCustomPropertyFunction.java
=> ensure parameter list is not empty (sources too)

ui/plugins/eu.esdihumboldt.hale.ui.views.mapping/src/eu/esdihumboldt/hale/ui/views/mapping/MappingView.java
Part of this was already accidentally merged in https://github.com/halestudio/hale/pull/285
=> use similar layouting in Mapping view as in Alignment view

ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/io/instance/FileValidateTarget.java
Do not add the selected validator if dialog is canceled.
=> Fix cancel behaviour when adding a validator

io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/reader/internal/wfs/WfsBackedGmlInstanceCollection.java
Prevent negative STARTINDEX and don't add MAXFEATURES/COUNT parameter
if maxFeatures is negative.
=> Add range checks for WFS parameters

io/plugins/eu.esdihumboldt.hale.io.haleconnect.ui/plugin.xml, io/plugins/eu.esdihumboldt.hale.io.haleconnect.ui/src/eu/esdihumboldt/hale/io/haleconnect/ui/HaleConnectLoginContentProvider.java, io/plugins/eu.esdihumboldt.hale.io.haleconnect.ui/src/eu/esdihumboldt/hale/io/haleconnect/ui/HaleConnectLoginDialog.java, io/plugins/eu.esdihumboldt.hale.io.haleconnect.ui/src/eu/esdihumboldt/hale/io/haleconnect/ui/HaleConnectLoginHandler.java, io/plugins/eu.esdihumboldt.hale.io.haleconnect.ui/src/eu/esdihumboldt/hale/io/haleconnect/ui/HaleConnectLogoutHandler.java, io/plugins/eu.esdihumboldt.hale.io.haleconnect.ui/src/eu/esdihumboldt/hale/io/haleconnect/ui/preferences/HaleConnectPreferencePage.java, io/plugins/eu.esdihumboldt.hale.io.haleconnect/src/eu/esdihumboldt/hale/io/haleconnect/HaleConnectService.java, io/plugins/eu.esdihumboldt.hale.io.haleconnect/src/eu/esdihumboldt/hale/io/haleconnect/HaleConnectSession.java, io/plugins/eu.esdihumboldt.hale.io.haleconnect/src/eu/esdihumboldt/hale/io/haleconnect/internal/HaleConnectServiceImpl.java, io/plugins/eu.esdihumboldt.hale.io.haleconnect/src/eu/esdihumboldt/hale/io/haleconnect/internal/HaleConnectSessionImpl.java
Addresses enhancement suggestions from #291.
Still open: Login on SWT version of Welcome Page
=> Improvements to hale connect login

ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/io/instance/InstanceExportWizard.java, ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/transformation/TransformDataWizardSourcePage.java
Fix problem described in #346 where validation is executed before actual transformation of data.
=> Fix validation in Transform Data wizards

ui/plugins/eu.esdihumboldt.hale.ui.application/HALE.product, ui/plugins/eu.esdihumboldt.hale.ui.application/plugin.xml, ui/plugins/eu.esdihumboldt.hale.ui.application/src/eu/esdihumboldt/hale/ui/application/internal/messages.properties, ui/plugins/eu.esdihumboldt.hale.ui.application/src/eu/esdihumboldt/hale/ui/application/internal/messages_de.properties, ui/plugins/eu.esdihumboldt.hale.ui.application/src/eu/esdihumboldt/hale/ui/application/internal/messages_es.properties
Changes the application title as described in halestudio/hale#310
=> Replace application title with "hale studio"

cst/plugins/eu.esdihumboldt.cst.functions.string/src/eu/esdihumboldt/cst/functions/string/RegexAnalysis.java, ui/plugins/eu.esdihumboldt.hale.ui.functions.core/src/eu/esdihumboldt/hale/ui/functions/core/RegexAnalysisParameterPage.java
Fix problems described in #319
=> Fix content assistance in RegEx Analysis

common/plugins/eu.esdihumboldt.hale.common.core/src/eu/esdihumboldt/hale/common/core/io/PathUpdate.java, common/plugins/eu.esdihumboldt.hale.common.core/src/eu/esdihumboldt/hale/common/core/io/project/impl/ArchiveProjectWriter.java
This addresses the problem described in #311.
The way the resources were copied to the temporary directory before could cause problems with files whose name contains character sequences that can be interpreted as being URL-encoded (like `%20`). In that case, the file name of the copied resource did not match the relative resource path in the save configuration.
To allow loading project archives created with previous versions, an additional resolving step is added to `PathUpdate`.
=> Fix resource file names in project archives

doc/plugins/eu.esdihumboldt.hale.doc.user.examples/src/eu/esdihumboldt/hale/doc/user/examples/internal/content/ExamplesContent.java
refs #312
Worked for me, you just have to wait a bit for the documentation to be generated for it to be actually displayed.
=> update mapping documentation for help example projects

ui/plugins/eu.esdihumboldt.hale.ui.application/HALE.product
- Use `https` throughout
- Update forum link
- Reanimate dead news link
=> Update links in About screen

cst/plugins/eu.esdihumboldt.cst.functions.core/src/eu/esdihumboldt/cst/functions/core/Create.java, cst/plugins/eu.esdihumboldt.cst.functions.groovy/plugin.xml, cst/plugins/eu.esdihumboldt.cst.functions.groovy/src/eu/esdihumboldt/cst/functions/groovy/GroovyCreate.java, ui/plugins/eu.esdihumboldt.hale.ui.functions.groovy/src/eu/esdihumboldt/hale/ui/functions/groovy/GroovyCreatePage.java
Essential for creating a large number of instances.
=> readd number parameter to Groovy Create

README.md
=> Fix typo in PostgreSQL name

common/plugins/eu.esdihumboldt.hale.common.schema/plugin.xml, common/plugins/eu.esdihumboldt.hale.common.schema/src/eu/esdihumboldt/hale/common/schema/model/constraint/property/CodeListAssociation.java, common/plugins/eu.esdihumboldt.hale.common.schema/src/eu/esdihumboldt/hale/common/schema/model/constraint/property/factory/CodeListAssocationFactory.java
=> add draft code list association constraint

common/plugins/eu.esdihumboldt.hale.common.cache/src/eu/esdihumboldt/hale/common/cache/Request.java
In headless mode, the `Request` class could not be used up to now to download resources because the `init()` threw an exception in non-OSGi environments. 
This poses a problem in cases where the fallback mechanism applied by the caller (if any) is not sophisticated enough to handle e.g. proxies or HTTP redirects (e.g. `URL.openStream()`).
=> Make Request class usable in headless mode

io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/reader/internal/wfs/WfsBackedGmlInstanceCollection.java
=> Don't add STARTINDEX parameter to unpaged WFS GetFeature requests

common/plugins/eu.esdihumboldt.hale.common.core/src/eu/esdihumboldt/hale/common/core/io/PathUpdate.java
Add fallback to PathUpdate that normalizes base and resource URLs w/ regard to a different amount of slashes after the scheme (e.g. file:/<path> vs. file:///<path>). Refs #425
=> Try normalized URIs in PathUpdate if prefixes don't match

io/plugins/eu.esdihumboldt.hale.io.xsd/src/eu/esdihumboldt/hale/io/xsd/reader/XmlSchemaReader.java
=> Try resolving schemas from resources before loading externally

ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/service/project/internal/ProjectServiceImpl.java
Resolves the problem described in #432
=> Reset project load content type on clean

cst/plugins/eu.esdihumboldt.cst.functions.groovy/plugin.xml, cst/plugins/eu.esdihumboldt.cst.functions.groovy/src/eu/esdihumboldt/cst/functions/groovy/helper/extension/HelperFunctionsExtension.java, cst/plugins/eu.esdihumboldt.cst.functions.groovy/src/eu/esdihumboldt/cst/functions/groovy/internal/GroovyObjectMetaClass.java
=> fix helper function invocation when function name conflicts w/ groovy default functions

io/plugins/eu.esdihumboldt.hale.io.xls/plugin.xml
...to support loading different sheets from the same file.
=> allow loading XLS files multiple times

util/plugins/eu.esdihumboldt.util.groovy.sandbox/src/eu/esdihumboldt/util/groovy/sandbox/internal/RestrictiveGroovyInterceptor.java
Also print qualified class names in `GroovyRestrictionException` messages
=> Whitelist java.sql.Date for use in Groovy scripts

common/plugins/eu.esdihumboldt.hale.common.codelist/src/eu/esdihumboldt/hale/common/codelist/config/CodeListAssociations.java, ui/plugins/eu.esdihumboldt.hale.ui.codelist/src/eu/esdihumboldt/hale/ui/codelist/service/CodeListService.java, ui/plugins/eu.esdihumboldt.hale.ui.codelist/src/eu/esdihumboldt/hale/ui/codelist/service/internal/CodeListServiceImpl.java, ui/plugins/eu.esdihumboldt.hale.ui.common.definition.editors/src/eu/esdihumboldt/hale/ui/common/definition/editors/DefaultPropertyEditor.java
=> Unassign code list if "Assign none" is selected in the dialog

CHANGELOG.md, io/plugins/eu.esdihumboldt.hale.io.shp.ui/plugin.xml, ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/io/config/CharsetConfigurationPage.java, ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/io/config/ShapefileCharsetConfigurationPage.java
=> Use value in .cpg to prefill charset dialog when importing shapefile

CHANGELOG.md, common/plugins/eu.esdihumboldt.hale.common.filter/src/eu/esdihumboldt/hale/common/filter/FilterGeoECqlImpl.java, doc/plugins/eu.esdihumboldt.hale.doc.user/contexts.xml, doc/plugins/eu.esdihumboldt.hale.doc.user/html/reference/cql_filter.html, ui/plugins/eu.esdihumboldt.hale.ui.filter/plugin.xml, ui/plugins/eu.esdihumboldt.hale.ui.filter/src/eu/esdihumboldt/hale/ui/filter/cql/CQLFilterField.java
Allow extended CQL expressions in filters (#455)
=> Allow ECQL expressions in CQLFilterField

io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/reader/internal/instance/StreamGmlHelper.java
Should solve https://github.com/halestudio/hale/issues/515
=> actually use CRS identified for geometry

ui/plugins/eu.esdihumboldt.hale.ui.views.mapping/src/eu/esdihumboldt/hale/ui/views/mapping/AlignmentView.java, ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/service/tasks/CellMessageTaskProvider.java, ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/service/tasks/internal/TaskServiceImpl.java
Don't notify `TaskServiceListeners` when no tasks were actually added/removed.
=> Fix task-related notifications

common/plugins/eu.esdihumboldt.hale.common.align.merge/src/eu/esdihumboldt/hale/common/align/merge/functions/JoinContext.java, common/plugins/eu.esdihumboldt.hale.common.align.merge/src/eu/esdihumboldt/hale/common/align/merge/functions/JoinMergeMigrator.java, common/plugins/eu.esdihumboldt.hale.common.align/src/eu/esdihumboldt/hale/common/align/model/functions/explanations/JoinExplanation.java, common/plugins/eu.esdihumboldt.hale.common.align/src/eu/esdihumboldt/hale/common/align/model/functions/join/JoinMigrator.java, common/plugins/eu.esdihumboldt.hale.common.align/src/eu/esdihumboldt/hale/common/align/model/functions/join/JoinParameter.java, cst/plugins/eu.esdihumboldt.cst.functions.core/src/eu/esdihumboldt/cst/functions/core/Join.java, cst/plugins/eu.esdihumboldt.cst.functions.core/src/eu/esdihumboldt/cst/functions/core/join/IndexJoinHandler.java, cst/plugins/eu.esdihumboldt.cst.functions.core/src/eu/esdihumboldt/cst/functions/core/join/JoinHandler.java, cst/plugins/eu.esdihumboldt.cst.functions.core/src/eu/esdihumboldt/cst/functions/core/join/JoinUtil.java, io/plugins/eu.esdihumboldt.hale.io.appschema.ui/src/eu/esdihumboldt/hale/io/appschema/ui/FeatureChainingConfigurationPage.java, io/plugins/eu.esdihumboldt.hale.io.appschema/src/eu/esdihumboldt/hale/io/appschema/writer/AppSchemaMappingUtils.java, io/plugins/eu.esdihumboldt.hale.io.appschema/src/eu/esdihumboldt/hale/io/appschema/writer/internal/JoinHandler.java, ui/plugins/eu.esdihumboldt.hale.ui.functions.core/src/eu/esdihumboldt/hale/ui/functions/core/JoinParameterPage.java, ui/plugins/eu.esdihumboldt.hale.ui.functions.groovy/src/eu/esdihumboldt/hale/ui/functions/groovy/GroovyJoinPage.java, ui/plugins/eu.esdihumboldt.hale.ui.functions.groovy/src/eu/esdihumboldt/hale/ui/functions/groovy/internal/GroovyJoinContentProvider.java
=> retain Join configuration when adding/removing types

ui/plugins/eu.esdihumboldt.hale.ui.util/src/eu/esdihumboldt/hale/ui/util/selector/AbstractViewerSelectionDialog.java, ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/service/align/resolver/UserFallbackEntityResolver.java, ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/service/align/resolver/internal/PropertyEntityResolverDialog.java, ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/service/align/resolver/internal/TypeEntityResolverDialog.java, ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/service/align/resolver/internal/ViewerEntityTray.java
See comments in https://github.com/halestudio/hale/issues/397
=> allow again to skip single entities, fix description

ui/plugins/eu.esdihumboldt.hale.ui/plugin.xml, ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/service/entity/internal/handler/PurgeConditionContextHandler.java
...and thus applying cell that related to the condition to the entities w/o condition.
Same as editing a condition, but in this case setting no condition.
=> support purging a condition

ui/plugins/eu.esdihumboldt.hale.ui.index/src/eu/esdihumboldt/hale/ui/index/internal/InstanceIndexUpdateServiceImpl.java
Map entry cannot be cast to Cell.
=> fix ClassCastException

ui/plugins/eu.esdihumboldt.hale.ui.filter/src/eu/esdihumboldt/hale/ui/filter/TypeFilterField.java
Prevent (long-running) filter updates at every keystroke as requested in #528.
=> Add type delay to type filter field

common/plugins/eu.esdihumboldt.hale.common.instance/src/eu/esdihumboldt/hale/common/instance/io/impl/AbstractInstanceValidator.java, io/plugins/eu.esdihumboldt.hale.io.schematron/src/eu/esdihumboldt/hale/io/schematron/validator/SchematronInstanceValidator.java, io/plugins/eu.esdihumboldt.hale.io.validation/src/eu/esdihumboldt/hale/io/validation/ProjectValidator.java, io/plugins/eu.esdihumboldt.hale.io.xml/src/eu/esdihumboldt/hale/io/xml/validator/XmlInstanceValidator.java
=> set a report type for instance validators

io/plugins/eu.esdihumboldt.hale.io.haleconnect.ui/src/eu/esdihumboldt/hale/io/haleconnect/ui/projects/HaleConnectTarget.java
Trying to fix layout problem described in #529
=> Update hale connect target page layout

platform/hale-platform.target
added xtraserver-config-util 1.0.0
=> updated reference to target platform

io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/writer/internal/DefaultMultipartHandler.java, io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/writer/internal/PerTypePartsHandler.java, io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/writer/internal/StreamGmlWriter.java
=> Support GZipped output when partitioning is active

doc/plugins/eu.esdihumboldt.hale.doc.user/html/new/3_4_0.xhtml, doc/plugins/eu.esdihumboldt.hale.doc.user/toc.xml, io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/writer/internal/DefaultMultipartHandler.java, io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/writer/internal/StreamGmlWriter.java, ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/transformation/TransformDataImportAdvisor.java
=> No passthrough if instances are partitioned by type

util/plugins/eu.esdihumboldt.util/src/eu/esdihumboldt/util/validator/LengthValidator.java, util/plugins/eu.esdihumboldt.util/src/eu/esdihumboldt/util/validator/NumberValidator.java
This addresses the problem described in #621
=> Add support for validating the size of value collections

io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/writer/internal/StreamGmlWriter.java
=> prevent NPE if container element is not found

io/plugins/eu.esdihumboldt.hale.io.xsd/src/eu/esdihumboldt/hale/io/xsd/model/ComplexContentHasValue.java, io/plugins/eu.esdihumboldt.hale.io.xsd/src/eu/esdihumboldt/hale/io/xsd/reader/XmlSchemaReader.java
Attempt at a minimal invasive solution for #645
=> allow content for complexContent types in some cases

ext/nonosgi/eu.esdihumboldt.hale.util.nonosgi/src/eu/esdihumboldt/hale/util/nonosgi/contenttype/ContentTypeManager.java
Try to fix hale-cli [build errors](https://builds.wetransform.to/job/hale/job/hale-cli~publish(devel)/285/testReport/)
=> Don't use uninitialized Activator in non-OSGi environment

io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/reader/internal/instance/StreamGmlHelper.java
Allow passing up the value of an `srsDimension` attribute at the coordinate level (e.g. in the `posList` element) and take it into account when creating the geometry. This addresses the problem in #627.
=> Support srsDimension attribute at coordinates level

common/plugins/eu.esdihumboldt.hale.common.headless/src/eu/esdihumboldt/hale/common/headless/impl/ProjectTransformationEnvironment.java
=> add possibility to copy ProjectTransformationEnvironment

io/plugins/eu.esdihumboldt.hale.io.xsd/src/eu/esdihumboldt/hale/io/xsd/anytype/CustomTypeContentHelper.java
No one to blame but me (probably programmed some Scala around that time).
Interesting though that the error did not surface in hale studio.
=> fix switch handling in CustomContentTypeHelper

io/plugins/eu.esdihumboldt.hale.io.haleconnect/src/eu/esdihumboldt/hale/io/haleconnect/HaleConnectProjectInfo.groovy
Addresses problem w/ hc project list described in #685
=> Prevent recursion caused by Groovy == comparison

common/plugins/eu.esdihumboldt.hale.common.headless/src/eu/esdihumboldt/hale/common/headless/transform/Transformation.java
=> Don't use streaming when Groovy Create/Retype functions are present

platform/hale-platform.target
Update resource cache bundles and remove appschema model
See
https://github.com/halestudio/hale-platform/pull/20
https://github.com/halestudio/hale-platform/pull/21
=> build: update target platform

ui/plugins/eu.esdihumboldt.hale.ui.application/HALE.product
Added missing ECF features to HALE product.
=> Fix failing HALE product validation after enabling remote software updates (#693)

ui/plugins/eu.esdihumboldt.hale.ui.application/plugin.xml
=> docs: update build year on splash screen

io/plugins/eu.esdihumboldt.hale.io.haleconnect/src/eu/esdihumboldt/hale/io/haleconnect/internal/HaleConnectServiceImpl.groovy
Fix up situation where suddently all organisations are dummy organisations.
=> fixup! fix(hc): handle cases where user/org information is unavailable

common/plugins/eu.esdihumboldt.hale.common.headless.orient/src/eu/esdihumboldt/hale/common/headless/orient/OrientTransformationSink.java
Makes `OrientInstanceSink` behave like `OrientInstanceService` and return only those instances in `getInstanceCollection()` for which `OInstance.inInserted()` is true.
Previously it could happen that in a headless transformation that instances that are substructures of the inserted instance were also written to the target, resulting in too many instances being written.
https://github.com/halestudio/hale/issues/774
=> fix(headless): return only inserted instances from instance sink

ext/styledmap/eu.esdihumboldt.hale.ui.views.styledmap/src/eu/esdihumboldt/hale/ui/views/styledmap/painter/StyledInstanceMarker.java
https://github.com/halestudio/hale/issues/732
=> fix : rendering of target geometries

io/plugins/eu.esdihumboldt.hale.io.gml.ui/plugin.xml, io/plugins/eu.esdihumboldt.hale.io.gml/plugin.xml, io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/writer/XPlanGmlInstanceWriter.java, io/plugins/eu.esdihumboldt.hale.io.gml/src/eu/esdihumboldt/hale/io/gml/writer/internal/StreamGmlWriter.java
Adds an XPlanGML writer that writes an `XPlanAuszug` root element.
https://github.com/halestudio/hale/issues/814
=> feat: add XPlanGML writer

doc/plugins/eu.esdihumboldt.hale.doc.user/html/introduction/introduction_dhp.html
I have changed the website link from www.wetransform.to to https://www.wetransform.to as it was not working correctly.
=> Fixed Link to the wetransform homepage as it was not working

platform/hale-platform.target, ui/plugins/eu.esdihumboldt.hale.ui.application/plugin.xml
=> Switch to new platform version

io/plugins/eu.esdihumboldt.hale.io.haleconnect.ui/src/eu/esdihumboldt/hale/io/haleconnect/ui/projects/HaleConnectTarget.java
Because permissions checks done as part of the login status update are executed
asynchronously, it is possible that the owner radio buttons are only activated
after the validity of the dialog is input is already determined. This leads to
the situation that a logged-in user can't create or update transformation
projects even if they have the correct permissions.
With this fix, the login status check and dialog validation are separated and
the dialog validation is retriggered once the asynchronous operation to
determine the user's permissions are completed.
=> fix: fix validity check of the hale»connect export dialog

common/plugins/eu.esdihumboldt.hale.common.test/Tests.product
Add the `org.eclipse.core.net` plugin to the Tests products
=> fixup! fix(ui): use IProxyService to apply proxy configuration in the UI

io/plugins/eu.esdihumboldt.hale.io.shp.test/src/eu/esdihumboldt/hale/io/shp/ShapefileInstanceWriterTest.groovy, io/plugins/eu.esdihumboldt.hale.io.shp/src/eu/esdihumboldt/hale/io/shp/writer/ShapefileInstanceWriter.java
This commit provides a fix for exporting the Shapefiles when some
of the instances are null in the attributes which caused the
improper schema creation. The change is done to add all the
attributes even if their their data is null.
This commit also provides a fix to truncate long column names
up to 9 characters. If column names are longer than 10 characters
then the library will not export their corresponding instance data.
ING-2971
=> fixup!feat: support to export data using shapefile writer

common/plugins/eu.esdihumboldt.hale.common.test/Tests.product, util/plugins/eu.esdihumboldt.util.resource.schemas.end/.project, util/plugins/eu.esdihumboldt.util.resource.schemas.end/.settings/org.eclipse.jdt.core.prefs, util/plugins/eu.esdihumboldt.util.resource.schemas.end/META-INF/MANIFEST.MF
This commit provides a fix for Jenkins build errors.
ING 2970
=> fixup! feat: add END-related schemas to presets

common/plugins/eu.esdihumboldt.hale.common.core/src/eu/esdihumboldt/hale/common/core/io/supplier/FilesIOSupplier.java, common/plugins/eu.esdihumboldt.hale.common.schema/src/eu/esdihumboldt/hale/common/schema/model/impl/ResourceSchemaSpace.java, io/plugins/eu.esdihumboldt.hale.io.shp.ui/src/eu/esdihumboldt/hale/io/shp/ui/TypeSelectionPage.java, ui/plugins/eu.esdihumboldt.hale.ui.util/src/eu/esdihumboldt/hale/ui/util/io/ExtendedFileFieldEditor.java, ui/plugins/eu.esdihumboldt.hale.ui.views.resources/src/eu/esdihumboldt/hale/ui/views/resources/internal/ResourcesLabelProvider.java, ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/io/IOWizard.java, ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/io/source/AbstractMultipleFilesSource.java, ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/io/source/AbstractMultipleFilesSourceFileFieldEditor.java
Fix selection of multiple files for windows and enable export provider
=> fixup! feat: enable selecting more than one file when loading schema

cst/plugins/eu.esdihumboldt.cst.functions.numeric/plugin.xml, cst/plugins/eu.esdihumboldt.cst.functions.numeric/src/eu/esdihumboldt/cst/functions/numeric/sequentialid/SequentialID.java, cst/plugins/eu.esdihumboldt.cst.functions.numeric/src/eu/esdihumboldt/cst/functions/numeric/sequentialid/SequentialIDConstants.java, ui/plugins/eu.esdihumboldt.hale.ui.functions.numeric/plugin.xml, ui/plugins/eu.esdihumboldt.hale.ui.functions.numeric/src/eu/esdihumboldt/hale/ui/functions/numeric/SequentialIDParameterPage.java
The default value is 1.
ING-3284
=> feat: add option to specify the initial value for the sequential ID generator function.

cst/plugins/eu.esdihumboldt.cst.functions.numeric/plugin.xml, cst/plugins/eu.esdihumboldt.cst.functions.numeric/src/eu/esdihumboldt/cst/functions/numeric/sequentialid/SequentialID.java, ui/plugins/eu.esdihumboldt.hale.ui.functions.numeric/src/eu/esdihumboldt/hale/ui/functions/numeric/SequentialIDParameterPage.java
The starting integer value of any ID sequence must be larger than 0.
ING-3284
=> fixup! feat: add option to specify the initial value for the sequential ID generator function.

io/plugins/eu.esdihumboldt.hale.io.shp.test/src/eu/esdihumboldt/hale/io/shp/ShapefileInstanceWriterTest.groovy, io/plugins/eu.esdihumboldt.hale.io.shp/src/eu/esdihumboldt/hale/io/shp/writer/ShapefileInstanceWriter.java
locally untested, will test with build
=> experimental fix for shapefile attrib length handling

common/plugins/eu.esdihumboldt.hale.common.convert.core/src/eu/esdihumboldt/hale/common/convert/core/AbstractStringToDateTimeTypeConverter.java, common/plugins/eu.esdihumboldt.hale.common.convert.core/src/eu/esdihumboldt/hale/common/convert/core/StringToInstantConverter.java, common/plugins/eu.esdihumboldt.hale.common.convert.core/src/eu/esdihumboldt/hale/common/convert/core/StringToJodaDateTimeConverter.java, common/plugins/eu.esdihumboldt.hale.common.convert.core/src/eu/esdihumboldt/hale/common/convert/core/StringToLocalDateConverter.java, common/plugins/eu.esdihumboldt.hale.common.convert.core/src/eu/esdihumboldt/hale/common/convert/core/StringToSqlTimestampConverter.java
Also adds the additional "null date" representation `0000-00-00T00:00:00.000`.
WGS-1982
=> Apply "null date" check to all classes that convert a String to a date/time object

util/plugins/eu.esdihumboldt.util.http/src/eu/esdihumboldt/util/http/client/metrics/PoolingHttpClientConnectionManagerMetrics.java
Use Prometheus compatible metric names.
ING-3601
=> fixup! feat: support collecting metrics on Request class HTTP clients

common/plugins/eu.esdihumboldt.hale.common.test/Tests.product
=> build: fix missing plugin error for Test.product

io/plugins/eu.esdihumboldt.hale.io.haleconnect.ui/src/eu/esdihumboldt/hale/io/haleconnect/ui/projects/ChooseHaleConnectProjectWizardPage.groovy, io/plugins/eu.esdihumboldt.hale.io.haleconnect.ui/src/eu/esdihumboldt/hale/io/haleconnect/ui/projects/OwnerFilterEntry.groovy
Compromise on immutability for OwnerFilterEntry after java 17
ING-3701
=> fix: upload project to hale connect

CHANGELOG.md
=> docs(changelog): add section for 5.0.0 release

build/config.groovy, common/plugins/eu.esdihumboldt.hale.common.core/src/eu/esdihumboldt/hale/common/core/io/project/impl/AbstractProjectReader.java, io/plugins/eu.esdihumboldt.hale.io.gml.ui/src/eu/esdihumboldt/hale/io/gml/ui/GmlWriterSettingsPage.java, io/plugins/eu.esdihumboldt.hale.io.jdbc.spatialite/src/eu/esdihumboldt/hale/io/jdbc/spatialite/internal/SpatiaLiteHelper.java, io/plugins/eu.esdihumboldt.hale.io.oml/src/eu/esdihumboldt/hale/io/oml/helper/NotSupportedTranslator.java, ui/plugins/eu.esdihumboldt.hale.ui.application/HALE.product, ui/plugins/eu.esdihumboldt.hale.ui.application/plugin.xml, ui/plugins/eu.esdihumboldt.hale.ui.application/src/eu/esdihumboldt/hale/ui/application/internal/messages.properties, ui/plugins/eu.esdihumboldt.hale.ui.application/src/eu/esdihumboldt/hale/ui/application/internal/messages_de.properties, ui/plugins/eu.esdihumboldt.hale.ui.application/src/eu/esdihumboldt/hale/ui/application/internal/messages_es.properties, ui/plugins/eu.esdihumboldt.hale.ui.firststeps/plugin.xml, ui/plugins/eu.esdihumboldt.hale.ui.util/plugin.xml, ui/plugins/eu.esdihumboldt.hale.ui/plugin.xml, ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/io/instance/crs/SelectCRSDialog.java
Changes spelling in the application except for the help pages.
=> refactor(ui): change spelling to hale»studio

doc/plugins/eu.esdihumboldt.hale.doc.application/Infocenter.product
=> build: resolve Infocenter.product dependencies

ui/plugins/eu.esdihumboldt.hale.ui.util/src/eu/esdihumboldt/hale/ui/util/proxy/ProxySettings.java
https://github.com/halestudio/hale/issues/1017
https://github.com/halestudio/hale/issues/727
=> fix: fix conversion of IProxyData list to array

app/plugins/eu.esdihumboldt.hale.app.cli.commands/src/eu/esdihumboldt/hale/app/cli/commands/alignment/ExportJsonCommand.groovy, app/plugins/eu.esdihumboldt.hale.app.cli.commands/src/eu/esdihumboldt/hale/app/cli/commands/alignment/MappingTableCommand.groovy, app/plugins/eu.esdihumboldt.hale.app.cli.commands/src/eu/esdihumboldt/hale/app/cli/commands/alignment/SvgDocumentationCommand.groovy, common/plugins/eu.esdihumboldt.hale.common.cli/META-INF/MANIFEST.MF, common/plugins/eu.esdihumboldt.hale.common.cli/src/eu/esdihumboldt/hale/common/cli/HaleCLIUtil.groovy, common/plugins/eu.esdihumboldt.hale.common.cli/src/eu/esdihumboldt/hale/common/cli/project/AbstractProjectCommand.groovy, common/plugins/eu.esdihumboldt.hale.common.cli/src/eu/esdihumboldt/hale/common/cli/project/ListProjectsCommand.groovy
=> refactor: update OptionAccessor with picocli imports

platform/hale-platform.target
=> fix: eliminate commons-text security vulnerability

io/plugins/eu.esdihumboldt.hale.io.shp.test/src/eu/esdihumboldt/hale/io/shp/ShapefileInstanceWriterTest.groovy, io/plugins/eu.esdihumboldt.hale.io.shp.ui/plugin.xml, io/plugins/eu.esdihumboldt.hale.io.shp.ui/src/eu/esdihumboldt/hale/io/shp/ui/ShapeTargetCRSConfigurationPage.java, io/plugins/eu.esdihumboldt.hale.io.shp.ui/src/eu/esdihumboldt/hale/io/shp/ui/TypeSelectionPage.java, io/plugins/eu.esdihumboldt.hale.io.shp/src/eu/esdihumboldt/hale/io/shp/writer/ShapefileInstanceWriter.java, ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/io/config/SimpleTargetCRSConfigurationPage.java
Export valid shapefiles for feature types with geometries. 
Displays a warning that feature types with no geometry will not be exported to shapefile.
ING-3974
=> feat: export valid shapefiles for mappings including feature types with no geometry

io/plugins/eu.esdihumboldt.hale.io.json/src/eu/esdihumboldt/hale/io/json/JsonInstanceReader.java, io/plugins/eu.esdihumboldt.hale.io.json/src/eu/esdihumboldt/hale/io/json/internal/AbstractJsonInstanceProcessor.java, io/plugins/eu.esdihumboldt.hale.io.json/src/eu/esdihumboldt/hale/io/json/internal/JsonInstanceCollection.java, io/plugins/eu.esdihumboldt.hale.io.json/src/eu/esdihumboldt/hale/io/json/internal/JsonInstanceProcessor.java, io/plugins/eu.esdihumboldt.hale.io.json/src/eu/esdihumboldt/hale/io/json/internal/JsonToInstance.java
...when reading Json instances.
ING-4046
=> refactor: refactor Json processing

common/plugins/eu.esdihumboldt.hale.common.schema.persist/src/eu/esdihumboldt/hale/common/schema/persist/hsd/MergeSchemas.java
=> fix: fix exporting HSD schemas for schemas with no namespace

io/plugins/eu.esdihumboldt.hale.io.json.test/src/eu/esdihumboldt/hale/io/json/test/InstanceToJsonTest.groovy, io/plugins/eu.esdihumboldt.hale.io.json/plugin.xml, io/plugins/eu.esdihumboldt.hale.io.json/src/eu/esdihumboldt/hale/io/json/JsonInstanceWriter.java, io/plugins/eu.esdihumboldt.hale.io.json/src/eu/esdihumboldt/hale/io/json/internal/InstanceToJson.java
This configuration can be added in
`<export-config>` element of `.halex`
project file as
`<setting name="numOfDecimalPlaces">14</setting>`
ING-3332
=> feat: configure decimal places in JsonInstanceWriter

io/plugins/eu.esdihumboldt.hale.io.json.test/src/eu/esdihumboldt/hale/io/json/test/JsonToInstanceTest.groovy, io/plugins/eu.esdihumboldt.hale.io.json/src/eu/esdihumboldt/hale/io/json/internal/JsonInstanceBuilder.groovy
=> fix: prefer properties with short path as GeoJson geometry property

io/plugins/eu.esdihumboldt.hale.io.xls.test/src/eu/esdihumboldt/hale/io/xls/test/reader/XLSReaderTest.java, io/plugins/eu.esdihumboldt.hale.io.xls/src/eu/esdihumboldt/hale/io/xls/reader/ReaderSettings.java, io/plugins/eu.esdihumboldt.hale.io.xls/src/eu/esdihumboldt/hale/io/xls/reader/XLSInstanceReader.java, io/plugins/eu.esdihumboldt.hale.io.xls/src/eu/esdihumboldt/hale/io/xls/writer/XLSInstanceWriter.java
Fix matching the type for an Excel sheet, refactor to use same logic in reader and writer.
ING-4062
=> fixup! feat: support reading multiple Excel sheets at once

.github/ISSUE_TEMPLATE/ask-a-question-on-hale-studio-usage.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/report-a-bug.md
Add issue template files for adding 
- a bug, 
- a feature request or 
- just send the user to the forum if they have a question
no-ING-related
=> feat: add issue template

common/plugins/eu.esdihumboldt.hale.common.align/src/eu/esdihumboldt/hale/common/align/model/transformation/tree/visitor/CellNodeValidator.java
=> refactor: improve error message for missing source node

io/plugins/eu.esdihumboldt.hale.io.topojson.test/src/eu/esdihumboldt/hale/io/topojson/test/TopoJsonInstanceWriterTest.groovy, io/plugins/eu.esdihumboldt.hale.io.topojson/src/eu/esdihumboldt/hale/io/topojson/TopoJsonInstanceWriter.java
Convert all the "null" String values into null value.
Update test for date values.
ING-3979
=> fix: TopoJSON encoding null values

io/plugins/eu.esdihumboldt.hale.io.topojson.test/src/eu/esdihumboldt/hale/io/topojson/test/TopoJsonInstanceWriterTest.groovy, io/plugins/eu.esdihumboldt.hale.io.topojson/src/eu/esdihumboldt/hale/io/topojson/TopoJsonInstanceWriter.java
convert String integer/number and String boolean into integer/number or boolean
ING-3979
=> fix: TopoJSON: Convert String integer/number and String boolean into integer/number or boolean

io/plugins/eu.esdihumboldt.hale.io.xls.ui/src/eu/esdihumboldt/hale/io/xls/ui/XLSSchemaTypePage.java, io/plugins/eu.esdihumboldt.hale.io.xls/src/eu/esdihumboldt/hale/io/xls/AbstractAnalyseTable.java, io/plugins/eu.esdihumboldt.hale.io.xls/src/eu/esdihumboldt/hale/io/xls/AnalyseXLSSchemaTable.java, io/plugins/eu.esdihumboldt.hale.io.xls/src/eu/esdihumboldt/hale/io/xls/XLSUtil.java, io/plugins/eu.esdihumboldt.hale.io.xls/src/eu/esdihumboldt/hale/io/xls/reader/XLSInstanceReader.java, io/plugins/eu.esdihumboldt.hale.io.xls/src/eu/esdihumboldt/hale/io/xls/reader/XLSSchemaReader.java
Add the correct number of instances also for the cases when the rows contains empty cell as result of a formula 
ING-4135
=> bug: add instances for empty rows

io/plugins/eu.esdihumboldt.hale.io.xls.test/src/eu/esdihumboldt/hale/io/xls/test/reader/XLSReaderTest.java
Remove commented method
ING-4151
=> fix: feat: add formatter for the date

ui/plugins/eu.esdihumboldt.hale.ui/src/eu/esdihumboldt/hale/ui/service/project/internal/ProjectVariablesPreferencePage.java
Removing of a variable via settings dialog is persisted in the project file upon save.
ING-4169
=> fix: hale: Removal of project variable is not persisted on save

io/plugins/eu.esdihumboldt.hale.io.csv.ui/src/eu/esdihumboldt/hale/io/csv/ui/TypeSelectionPage.java
Add a combo box with different patterns for the date formatter. This pattern is then used when importing cells of type Date.
ING-4165
=> feat:  add GUI parameter to select date formatter for the Excel importer

doc/plugins/eu.esdihumboldt.hale.doc.user/html/reference/export/export.html, doc/plugins/eu.esdihumboldt.hale.doc.user/html/tasks/data/save_transformation.html, doc/plugins/eu.esdihumboldt.hale.doc.user/toc.xml
Replaces https://github.com/halestudio/hale/pull/1093
=> docs: link to full list of exports

io/plugins/eu.esdihumboldt.hale.io.csv.ui/src/eu/esdihumboldt/hale/io/csv/ui/TypeSelectionPage.java, io/plugins/eu.esdihumboldt.hale.io.csv/src/eu/esdihumboldt/hale/io/csv/reader/internal/CSVInstanceCollection.java
Fixup the 'custom format'.
ING-4165
=> fixup! feat: add parameter for date formatter Excel and CSV importer

CHANGELOG.md, doc/plugins/eu.esdihumboldt.hale.doc.user/html/new/5_1_0.xhtml
Update list of changes into the CHANGELOG file.
ING-3990
=> fixup! feat: hale»studio 5.1.0

ui/plugins/eu.esdihumboldt.hale.ui.application/plugin.xml
Cherry-pick @florianesser's commit with the changes to the splash year.
ING-3990
=> refactor: update year in splash copyright notice

io/features/eu.esdihumboldt.hale.io.feature.unsafe/.project, io/features/eu.esdihumboldt.hale.io.feature.unsafe/.settings/org.eclipse.core.resources.prefs, io/features/eu.esdihumboldt.hale.io.feature.unsafe/build.properties, io/features/eu.esdihumboldt.hale.io.feature.unsafe/feature.xml
...to easily be able to include them when running hale studio from Eclipse.
=> refactor: add feature for unsafe IO providers

platform/hale-platform.target
TSML schemas updated
See https://github.com/wetransform/offline-resources/commit/3b4871618a36c2585227a4f66b04f9566b51f2bc
=> build: update offline resource

platform/hale-platform.target
Updates include small improvements to text output when running tests.
=> build(deps): update equinox-test update site

.github/workflows/publish.yml, build/buildSrc/build.gradle
Exclude resolver-api to see if build is successful.
=> chore(deps): update all non-major dependencies

.github/workflows/check.yml, .github/workflows/codeql.yml, .github/workflows/publish.yml
=> ci: add Trivy vulnerability check and CodeQL static analysis 

ext/styledmap/de.fhg.igd.mapviewer.server.wms/src/de/fhg/igd/mapviewer/server/wms/capabilities/WMSCapabilities.java, ext/styledmap/org.jdesktop.swingx.mapviewer/src/org/jdesktop/swingx/mapviewer/util/GeoUtil.java, io/plugins/eu.esdihumboldt.hale.io.codelist.xml/src/eu/esdihumboldt/hale/io/codelist/inspire/reader/INSPIRECodeListReader.java
Solve the issues related to vulnerabilities raised by CodeQL scanning for the XML external entity in user-controlled data.
ING-4371
=> fix: resolve XML external entity in user-controlled data

common/plugins/eu.esdihumboldt.hale.common.headless.orient/.settings/org.eclipse.jdt.core.prefs, common/plugins/eu.esdihumboldt.hale.common.headless.orient/META-INF/MANIFEST.MF, common/plugins/eu.esdihumboldt.hale.common.headless.orient/src/eu/esdihumboldt/hale/common/headless/orient/OrientTransformationSink.java, io/plugins/eu.esdihumboldt.hale.io.gml.test/src/eu/esdihumboldt/hale/io/gml/reader/internal/StreamGmlReaderTest.groovy
...to avoid the sink being closed while asynchronous operations are still pending.
ING-4479
Fix ported from https://github.com/halestudio/hale-core/pull/116
=> fix: wait until adding instance to sink is complete
